export const PROVIDERS = Object.freeze([
  {
    id: 'auto', name: 'Orb Auto', badge: 'AUTO', kind: 'virtual', keyless: true,
    baseUrl: '', env: null, signup: '', discover: false,
    free: 'Falls back across ready local and keyless cloud routes.', models: ['free'],
  },
  {
    id: 'ollama', name: 'Ollama', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:11434/v1', modelsUrl: 'http://127.0.0.1:11434/api/tags',
    env: null, signup: 'https://ollama.com/download',
    free: 'Runs on your machine; no account, key, or usage charge.',
    models: ['qwen2.5:1.5b'],
  },
  {
    id: 'llamacpp', name: 'llama.cpp', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/ggml-org/llama.cpp',
    free: 'Runs on your machine; no account, key, or usage charge.', models: [],
  },
  {
    id: 'lmstudio', name: 'LM Studio', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:1234/v1', env: null,
    signup: 'https://lmstudio.ai',
    free: 'Discovers models served by LM Studio on its standard local port.', models: [],
  },
  {
    id: 'vllm', name: 'vLLM', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: null,
    signup: 'https://github.com/vllm-project/vllm',
    free: 'Connects to a local vLLM OpenAI-compatible server.', models: [],
  },
  {
    id: 'localai', name: 'LocalAI', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/mudler/LocalAI',
    free: 'Connects to a local LocalAI server; override the endpoint if its port differs.', models: [],
  },
  {
    id: 'jan', name: 'Jan', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:1337/v1', env: null,
    signup: 'https://jan.ai',
    free: 'Discovers models exposed by Jan’s local OpenAI-compatible API.', models: [],
  },
  {
    id: 'koboldcpp', name: 'KoboldCpp', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:5001/v1', env: null,
    signup: 'https://github.com/LostRuins/koboldcpp',
    free: 'Connects to KoboldCpp’s local OpenAI-compatible endpoint.', models: [],
  },
  {
    id: 'gpt4all', name: 'GPT4All', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:4891/v1', env: null,
    signup: 'https://github.com/nomic-ai/gpt4all/wiki/Local-API-Server',
    free: 'Discovers models from GPT4All Desktop’s optional local API server.', models: [],
  },
  {
    id: 'textgen', name: 'Text Generation WebUI', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:5000/v1', env: null,
    signup: 'https://github.com/oobabooga/text-generation-webui',
    free: 'Connects to the local OpenAI-compatible API started with `--api`.', models: [],
  },
  {
    id: 'llama-swap', name: 'llama-swap', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/mostlygeek/llama-swap',
    free: 'Discovers locally configured models and starts their backend on demand.', models: [],
  },
  {
    id: 'pollinations', name: 'Pollinations', badge: 'KEYLESS', kind: 'community', keyless: true,
    baseUrl: 'https://text.pollinations.ai/openai', env: 'POLLINATIONS_API_KEY', optionalKey: true,
    signup: 'https://enter.pollinations.ai',
    free: 'Keyless community access is rate-limited; an optional key raises limits.',
    models: ['openai-fast'],
  },
  {
    id: 'github', name: 'GitHub Models', badge: 'FREE RETIRED', kind: 'cloud', keyless: false,
    baseUrl: 'https://models.github.ai/inference', env: 'GITHUB_TOKEN',
    signup: 'https://github.com/marketplace/models',
    free: 'The free tier retired July 30, 2026; kept for accounts that still have API access.',
    models: ['openai/gpt-4.1-mini', 'openai/gpt-4o-mini', 'deepseek/DeepSeek-V3-0324', 'meta/Llama-4-Scout-17B-16E-Instruct'],
  },
  {
    id: 'openrouter', name: 'OpenRouter', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://openrouter.ai/api/v1', env: 'OPENROUTER_API_KEY',
    signup: 'https://openrouter.ai/settings/keys',
    free: 'Models ending in :free have separate rate limits and no token charge.',
    modelPolicy: 'free-suffix',
    models: ['openrouter/free', 'deepseek/deepseek-r1-0528:free', 'qwen/qwen3-coder:free', 'meta-llama/llama-3.3-70b-instruct:free'],
  },
  {
    id: 'groq', name: 'GroqCloud', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.groq.com/openai/v1', env: 'GROQ_API_KEY',
    signup: 'https://console.groq.com/keys',
    free: 'Developer plan has published per-model rate limits.',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'openai/gpt-oss-20b', 'openai/gpt-oss-120b'],
  },
  {
    id: 'cerebras', name: 'Cerebras Inference', badge: 'TRIAL', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.cerebras.ai/v1', env: 'CEREBRAS_API_KEY',
    signup: 'https://cloud.cerebras.ai',
    free: 'Currently trial credit and payment verification, not a permanent card-free tier.',
    models: ['llama3.1-8b', 'gpt-oss-120b', 'qwen-3-32b'],
  },
  {
    id: 'gemini', name: 'Google Gemini', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai', env: 'GEMINI_API_KEY',
    signup: 'https://aistudio.google.com/app/apikey',
    free: 'Google AI Studio offers a rate-limited free tier in supported regions.',
    models: ['gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemma-3-27b-it'],
  },
  {
    id: 'mistral', name: 'Mistral La Plateforme', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.mistral.ai/v1', env: 'MISTRAL_API_KEY',
    signup: 'https://console.mistral.ai/api-keys',
    free: 'Experiment plan is rate-limited and may require account verification.',
    models: ['mistral-small-latest', 'open-mistral-nemo', 'codestral-latest'],
  },
  {
    id: 'nvidia', name: 'NVIDIA NIM', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://integrate.api.nvidia.com/v1', env: 'NVIDIA_API_KEY',
    signup: 'https://build.nvidia.com',
    free: 'Developer API access includes a limited evaluation allowance.',
    models: ['meta/llama-3.1-8b-instruct', 'deepseek-ai/deepseek-r1', 'qwen/qwen3-coder-480b-a35b-instruct'],
  },
  {
    id: 'sambanova', name: 'SambaNova Cloud', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.sambanova.ai/v1', env: 'SAMBANOVA_API_KEY',
    signup: 'https://cloud.sambanova.ai/apis',
    free: 'Free developer access is rate-limited.',
    models: ['Meta-Llama-3.3-70B-Instruct', 'DeepSeek-R1', 'Qwen3-32B'],
  },
  {
    id: 'huggingface', name: 'Hugging Face Inference', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://router.huggingface.co/v1', env: 'HF_TOKEN',
    signup: 'https://huggingface.co/settings/tokens',
    free: 'Free accounts receive a small monthly inference allowance.',
    models: ['meta-llama/Llama-3.1-8B-Instruct', 'Qwen/Qwen2.5-Coder-32B-Instruct', 'deepseek-ai/DeepSeek-R1:fastest'],
  },
  {
    id: 'siliconflow', name: 'SiliconFlow', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.siliconflow.com/v1', env: 'SILICONFLOW_API_KEY',
    signup: 'https://cloud.siliconflow.com/account/ak',
    free: 'New accounts may receive promotional balance; terms can change.',
    models: ['Qwen/Qwen2.5-7B-Instruct', 'deepseek-ai/DeepSeek-V3', 'THUDM/GLM-4-9B-0414'],
  },
  {
    id: 'chutes', name: 'Chutes', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://llm.chutes.ai/v1', env: 'CHUTES_API_KEY',
    signup: 'https://chutes.ai',
    free: 'Current public inference is pay-per-token; retained as an optional direct provider.',
    models: ['deepseek-ai/DeepSeek-V3-0324', 'Qwen/Qwen3-32B', 'unsloth/gemma-3-27b-it'],
  },
  {
    id: 'cohere', name: 'Cohere', badge: 'FREE EVAL', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.cohere.ai/compatibility/v1', env: 'COHERE_API_KEY',
    signup: 'https://dashboard.cohere.com/api-keys',
    free: 'Evaluation keys are free, limited to 1,000 calls/month and per-model RPM limits.',
    models: ['command-a-plus-05-2026', 'command-a-03-2025', 'command-r-plus', 'command-r7b-12-2024'],
  },
  {
    id: 'cloudflare', name: 'Cloudflare Workers AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'CLOUDFLARE_AI_BASE_URL', requiresBaseUrl: true, env: 'CLOUDFLARE_API_TOKEN',
    signup: 'https://dash.cloudflare.com/profile/api-tokens',
    free: 'Daily Workers AI allocation; set the account-specific OpenAI endpoint with `orb endpoint set cloudflare`.',
    models: ['@cf/meta/llama-3.3-70b-instruct-fp8-fast', '@cf/openai/gpt-oss-120b', '@cf/qwen/qwen2.5-coder-32b-instruct'],
  },
  {
    id: 'fireworks', name: 'Fireworks AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.fireworks.ai/inference/v1', env: 'FIREWORKS_API_KEY',
    signup: 'https://app.fireworks.ai/settings/users/api-keys',
    free: 'Selected access without a payment method is account-wide rate-limited.',
    models: ['accounts/fireworks/models/llama-v3p3-70b-instruct', 'accounts/fireworks/models/gpt-oss-120b'],
  },
  {
    id: 'zai', name: 'Z.AI Open Platform', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.z.ai/api/paas/v4', env: 'ZAI_API_KEY',
    signup: 'https://z.ai/manage-apikey/apikey-list',
    free: 'Flash model input, output, and cache pricing is published as free.',
    models: ['glm-4.7-flash', 'glm-4.5-flash', 'glm-4.6v-flash'],
  },
  {
    id: 'novita', name: 'Novita AI', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.novita.ai/openai', env: 'NOVITA_API_KEY',
    signup: 'https://novita.ai/settings/key-management',
    free: 'Selected models are priced at zero; provider does not publish one global quota.',
    models: ['inclusionai/Ling-3.0-flash', 'moonshotai/kimi-k2-instruct-0905'],
  },
  {
    id: 'dashscope', name: 'Alibaba Model Studio', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://dashscope-us.aliyuncs.com/compatible-mode/v1', env: 'DASHSCOPE_API_KEY',
    signup: 'https://bailian.console.alibabacloud.com/',
    free: 'Model-dependent free quotas; endpoint and key must belong to the same region.',
    models: ['qwen3.6-flash', 'qwen-plus', 'qwen-turbo', 'qwen3-coder-plus'],
  },
  {
    id: 'moonshot', name: 'Moonshot AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.moonshot.ai/v1', env: 'MOONSHOT_API_KEY',
    signup: 'https://platform.moonshot.ai/console/api-keys',
    free: 'Model-dependent account quota; no card required by the reviewed provider list.',
    models: ['kimi-k2-0905-preview', 'moonshot-v1-8k', 'moonshot-v1-128k'],
  },
  {
    id: 'modelscope', name: 'ModelScope', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api-inference.modelscope.cn/v1', env: 'MODELSCOPE_SDK_TOKEN',
    signup: 'https://modelscope.cn/my/myaccesstoken',
    free: 'Selected hosted open models share a daily free request allowance.',
    models: ['MiniMax/MiniMax-M2.5', 'inclusionAI/Ling-2.6-1T', 'deepseek-ai/DeepSeek-V4-Flash', 'ZhipuAI/GLM-5', 'Qwen/Qwen3-Coder-480B-A35B-Instruct'],
  },
  {
    id: 'ollama-cloud', name: 'Ollama Cloud', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://ollama.com/api', modelsUrl: 'https://ollama.com/api/tags', protocol: 'ollama', env: 'OLLAMA_API_KEY',
    signup: 'https://ollama.com/settings/keys',
    free: 'Account cloud models use session and weekly free-plan limits.',
    models: ['gpt-oss:120b', 'gpt-oss:20b', 'qwen3-coder:480b', 'deepseek-v3.1:671b', 'minimax-m2.5'],
  },
  {
    id: 'llm7', name: 'LLM7', badge: 'KEYLESS', kind: 'community', keyless: true,
    baseUrl: 'https://api.llm7.io/v1', env: 'LLM7_API_KEY', optionalKey: true,
    signup: 'https://token.llm7.io', modelPolicy: 'included-tier',
    free: 'Anonymous quota works without a key; a free token increases the request limit.',
    models: ['gpt-oss:20b', 'codestral-latest', 'minimax-m2.7', 'mistral-Nemo-Instruct-2407'],
  },
  {
    id: 'ovh', name: 'OVHcloud AI Endpoints', badge: 'KEYLESS', kind: 'cloud', keyless: true,
    baseUrl: 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1', env: 'OVH_AI_ENDPOINTS_ACCESS_TOKEN', optionalKey: true,
    signup: 'https://www.ovhcloud.com/en/public-cloud/ai-endpoints/catalog/', chatOnly: true,
    free: 'Anonymous inference is limited to roughly 2 RPM; a token provides account limits.',
    models: ['Qwen3.5-397B-A17B', 'Qwen3.6-27B', 'Meta-Llama-3_3-70B-Instruct', 'gpt-oss-120b', 'gpt-oss-20b', 'Qwen3-Coder-30B-A3B-Instruct'],
  },
  {
    id: 'kilo', name: 'Kilo Gateway', badge: 'KEYLESS', kind: 'community', keyless: true,
    baseUrl: 'https://api.kilo.ai/api/gateway', env: 'KILO_API_KEY', optionalKey: true,
    signup: 'https://kilo.ai', modelPolicy: 'free-suffix',
    free: 'Free-suffixed models allow anonymous access, currently limited per IP.',
    models: ['stepfun/step-3.7-flash:free', 'poolside/laguna-s-2.1:free', 'tencent/hy3:free', 'nvidia/nemotron-3-ultra-550b-a55b:free', 'nvidia/nemotron-3-super-120b-a12b:free', 'cohere/north-mini-code:free', 'openrouter/free'],
  },
  {
    id: 'opencode', name: 'OpenCode Free Gateway', badge: 'KEYLESS', kind: 'community', keyless: true,
    baseUrl: 'https://console.opencode.ai/inference/openai/v1', env: 'OPENCODE_API_KEY', optionalKey: true,
    signup: 'https://console.opencode.ai', discover: false,
    free: 'The provider documents no-key access for its current free chat models.',
    models: ['big-pickle', 'deepseek-v4-flash-free', 'mimo-v2.5-free', 'nemotron-3-ultra-free', 'north-mini-code-free', 'laguna-s-2.1-free', 'ling-3.0-flash-free'],
  },
  {
    id: 'aion', name: 'Aion Labs', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.aionlabs.ai/v1', env: 'AIONLABS_API_KEY',
    signup: 'https://www.aionlabs.ai',
    free: 'Free account inference is limited by requests and daily tokens.',
    models: ['aion-2-5', 'aion-2-0', 'aion-rp-1-0-8b'],
  },
  {
    id: 'agnes', name: 'Agnes AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://apihub.agnes-ai.com/v1', env: 'AGNES_API_KEY',
    signup: 'https://platform.agnes-ai.com/settings/apiKeys',
    free: 'Free account models have provider-published per-minute limits.',
    models: ['agnes-1.5-flash', 'agnes-2.0-flash'],
  },
  {
    id: 'glhf', name: 'GLHF.chat', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://glhf.chat/api/openai/v1', env: 'GLHF_API_KEY',
    signup: 'https://glhf.chat/',
    free: 'Community-hosted free model routes are advertised without a token quota.',
    models: ['meta-llama/Meta-Llama-3.1-70B-Instruct', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
  },
  {
    id: 'ai21', name: 'AI21 Labs', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.ai21.com/studio/v1', env: 'AI21_API_KEY',
    signup: 'https://studio.ai21.com/account/api-key',
    free: 'Free developer access is limited to the supported Jamba models.',
    models: ['jamba-large-2', 'jamba-mini-2'],
  },
  {
    id: 'nscale', name: 'Nscale', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://inference.api.nscale.com/v1', env: 'NSCALE_API_KEY',
    signup: 'https://console.nscale.com/',
    free: 'Free inference is subject to the provider fair-use policy.',
    models: ['llama-3-3-70b-instruct', 'deepseek-r1-distill-llama-70b'],
  },
  {
    id: 'nebius', name: 'Nebius AI Studio', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.studio.nebius.com/v1', env: 'NEBIUS_API_KEY',
    signup: 'https://studio.nebius.com/settings/api-keys',
    free: 'New-account or renewable credits are tier-dependent; usage may become paid.',
    models: ['Qwen/Qwen3-235B-A22B', 'deepseek-ai/DeepSeek-V3-0324', 'meta-llama/Llama-3.3-70B-Instruct'],
  },
  {
    id: 'xai', name: 'xAI', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.x.ai/v1', env: 'XAI_API_KEY',
    signup: 'https://console.x.ai',
    free: 'Account credits and eligibility vary; the direct API is not universally zero-cost.',
    models: ['grok-3-mini', 'grok-3', 'grok-4-fast-non-reasoning'],
  },
  {
    id: 'vercel', name: 'Vercel AI Gateway', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://ai-gateway.vercel.sh/v1', env: 'VERCEL_AI_GATEWAY_API_KEY',
    signup: 'https://vercel.com/dashboard/ai-gateway',
    free: 'Team accounts receive $5/month until they purchase paid gateway credits.',
    models: ['openai/gpt-oss-120b', 'moonshotai/kimi-k2', 'google/gemini-2.5-flash-lite', 'meta/llama-3.3-70b-instruct'],
  },
  {
    id: 'airforce', name: 'Api.Airforce', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.airforce/v1', env: 'AIRFORCE_API_KEY', publicCatalog: true,
    signup: 'https://api.airforce/', modelPolicy: 'free-tier', chatOnly: true,
    autoModel: 'gemma3-270m:free', autoPriority: 40,
    free: 'Free plan has 1 RPM and 1,000 RPD; Orb lists only explicit zero-cost routes.',
    models: ['gemma3-270m:free'],
  },
  {
    id: 'bazaarlink', name: 'BazaarLink', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://bazaarlink.ai/api/v1', env: 'BAZAARLINK_API_KEY', publicCatalog: true,
    signup: 'https://bazaarlink.ai', modelPolicy: 'free-suffix',
    autoModel: 'auto:free', autoPriority: 30,
    headers: { 'x-free-fallback': 'false' },
    free: 'Free models have per-model daily quotas; Orb disables fallback into paid usage.',
    models: ['auto:free', 'deepseek/deepseek-v4-flash:free', 'qwen/qwen3.7-flash:free'],
  },
  {
    id: 'literouter', name: 'LiteRouter', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.literouter.com/v1', env: 'LITEROUTER_API_KEY',
    signup: 'https://literouter.com', modelPolicy: 'free-suffix',
    autoModel: 'gpt-oss-120b:free', autoPriority: 10,
    free: 'Free-suffixed routes have a seven-second cooldown and no token price.',
    models: [
      'claude-haiku-4.5-cheap:free', 'deepseek-r1-0528:free', 'deepseek-r1:free',
      'deepseek-reasoner:free', 'deepseek-v3-0324:free', 'deepseek-v3.1-terminus:free',
      'deepseek-v3.1:free', 'deepseek-v3.2:free', 'deepseek-v3:free',
      'gemini-2.5-flash-lite:free', 'gemini-2.5-flash:free', 'gemma-3-27b-it:free',
      'gemma-4-31b:free', 'gpt-4.1-mini:free', 'gpt-4.1-nano:free', 'gpt-4o-mini:free',
      'gpt-5-nano:free', 'gpt-oss-120b:free', 'gpt-oss-20b:free',
      'grok-4.1-fast-reasoning:free', 'l3-8b-lunaris:free', 'llama-3-8b-instruct:free',
      'llama-3.1-8b-instruct:free', 'llama-3.3-70b-instruct-turbo:free',
      'minimax-m2.7:free', 'ministral-3b-2512:free', 'mistral-large-3:free',
      'mistral-nemo-instruct-2407:free', 'mistral-small-24b-instruct-2501:free',
      'mythomax-l2-13b:free', 'nemotron-3-nano:free', 'openrouter:free', 'qwen3.5:free',
    ],
  },
  {
    id: 'llm-kiwi', name: 'LLM.kiwi', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://api.llm.kiwi/v1', env: 'LLM_KIWI_API_KEY', publicCatalog: true,
    signup: 'https://llm.kiwi',
    free: 'Free account requires no card and provides a rate-limited `auto` route.',
    models: ['auto'],
  },
  {
    id: 'publicai', name: 'Public AI Gateway', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://api.publicai.co/v1', env: 'PUBLICAI_API_KEY',
    signup: 'https://platform.publicai.co',
    autoModel: 'swiss-ai/apertus-70b-instruct', autoPriority: 20,
    headers: { 'user-agent': 'orb-route/0.5.0' },
    free: 'Public-interest inference tier with a provider-published request limit.',
    models: ['swiss-ai/apertus-70b-instruct', 'swiss-ai/Apertus-8B-Instruct-2509', 'aisingapore/Qwen-SEA-LION-v4-32B-IT', 'aisingapore/Gemma-SEA-LION-v4-27B-IT', 'allenai/Olmo-3-32B-Think', 'allenai/Olmo-3-7B-Instruct', 'utter-project/EuroLLM-22B-Instruct-2512'],
  },
  {
    id: 'morph', name: 'Morph', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.morphllm.com/v1', env: 'MORPH_API_KEY',
    signup: 'https://www.morphllm.com',
    free: 'Free allowance includes 200 requests each month; further usage is metered.',
    models: ['morph-v3-large', 'morph-v3-fast', 'morph-glm52-744b', 'morph-qwen35-397b', 'morph-qwen36-27b', 'morph-minimax3-428b', 'morph-dsv4flash'],
  },
  {
    id: 'ant-ling', name: 'Ant Ling', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.ant-ling.com/v1', env: 'ANT_LING_API_KEY',
    signup: 'https://developer.ant-ling.com/en/docs/getting-started/quickstart/',
    free: 'Account allowance resets at 500,000 tokens/day; paid overage requires billing setup.',
    models: ['Ling-3.0-flash', 'Ling-2.6-1T', 'Ling-2.6-flash', 'Ring-2.6-1T'],
  },
  {
    id: 'anyapi', name: 'AnyAPI AI', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.anyapi.ai/v1', env: 'ANYAPI_API_KEY',
    signup: 'https://anyapi.ai', modelPolicy: 'free-suffix',
    autoModel: 'nvidia/nemotron-3-nano-30b-a3b:free', autoPriority: 12,
    free: 'Free plan includes 100,000 anyTokens per day; Orb routes only explicit :free models.',
    models: [
      'google/gemma-4-26b-a4b-it:free', 'nvidia/nemotron-3-nano-30b-a3b:free',
      'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
      'nvidia/nemotron-3-ultra-550b-a55b:free', 'nvidia/nemotron-nano-12b-v2-vl:free',
      'nvidia/nemotron-nano-9b-v2:free',
    ],
  },
  {
    id: 'fastrouter', name: 'FastRouter', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.fastrouter.ai/api/v1', env: 'FASTROUTER_API_KEY', publicCatalog: true,
    signup: 'https://fastrouter.ai', modelPolicy: 'free-suffix', chatOnly: true,
    autoModel: 'openai/gpt-oss-120b:free', autoPriority: 14,
    free: 'Free-suffixed models have zero token pricing and small daily request limits.',
    models: [
      'openai/gpt-oss-120b:free', 'openai/gpt-oss-20b:free', 'google/gemma4-26b:free',
      'nvidia/nemotron-3-nano-30b:free', 'nvidia/nemotron-3-super:free',
      'sarvam/sarvam-105b:free',
    ],
  },
  {
    id: 'routeway', name: 'Routeway', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.routeway.ai/v1', env: 'ROUTEWAY_API_KEY', publicCatalog: true,
    signup: 'https://routeway.ai', modelPolicy: 'free-suffix', chatOnly: true,
    autoModel: 'step-3.7-flash:free', autoPriority: 16,
    free: 'Free-suffixed models are capped at 5 RPM and 200 requests per day.',
    models: [
      'step-3.7-flash:free', 'gemma-4-31b-it:free', 'nemotron-3-nano-30b-a3b:free',
      'laguna-xs.2:free', 'laguna-m.1:free', 'nemotron-nano-9b-v2:free',
      'gpt-oss-120b:free', 'llama-3.2-3b-instruct:free', 'llama-3.2-1b-instruct:free',
      'llama-3.1-8b-instruct:free', 'llama-3.3-70b-instruct:free',
    ],
  },
  {
    id: 'naga', name: 'NagaAI', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.naga.ac/v1', env: 'NAGA_API_KEY', publicCatalog: true,
    signup: 'https://naga.ac', modelPolicy: 'free-suffix', chatOnly: true,
    autoModel: 'nemotron-3-super-120b-a12b:free', autoPriority: 18,
    free: 'Orb exposes only zero-priced :free chat routes from NagaAI’s public catalog.',
    models: [
      'nemotron-3-ultra-550b-a55b:free', 'nemotron-3-super-120b-a12b:free',
      'llama-3.3-70b-instruct:free', 'sonar:free', 'llama-4-scout-17b-16e-instruct:free',
    ],
  },
  {
    id: 'poixe', name: 'Poixe AI', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.poixe.com/v1', env: 'POIXE_API_KEY', discover: false,
    signup: 'https://poixe.com', modelPolicy: 'free-suffix',
    autoModel: 'qwen3-8b:free', autoPriority: 25,
    free: 'Free-suffixed chat models have separate daily-reset quotas; Orb seeds only models marked free by Poixe.',
    models: [
      'gpt-3.5-turbo:free', 'gpt-3.5-turbo-0125:free', 'gpt-4.1:free',
      'gpt-4.1-2025-04-14:free', 'gpt-4.1-mini:free', 'gpt-4.1-mini-2025-04-14:free',
      'gpt-4.1-nano:free', 'gpt-4.1-nano-2025-04-14:free', 'gpt-4o:free',
      'gpt-4o-2024-08-06:free', 'gpt-4o-2024-11-20:free', 'gpt-4o-mini:free',
      'gpt-4o-mini-2024-07-18:free', 'gpt-5:free', 'gpt-5-2025-08-07:free',
      'gpt-5-chat-latest:free', 'gpt-5-mini:free', 'gpt-5-mini-2025-08-07:free',
      'gpt-5-nano:free', 'gpt-5-nano-2025-08-07:free', 'gpt-5.1:free',
      'gpt-5.1-2025-11-13:free', 'gpt-5.2:free', 'gpt-5.2-2025-12-11:free',
      'gpt-oss-120b:free', 'gpt-oss-20b:free', 'o1-mini:free', 'o1-mini-2024-09-12:free',
      'o3-mini:free', 'o3-mini-2025-01-31:free', 'o4-mini:free', 'o4-mini-2025-04-16:free',
      'claude-sonnet-4-20250514:free', 'claude-sonnet-4-5-20250929:free',
      'deepseek-chat:free', 'deepseek-reasoner:free', 'doubao-1-5-lite-32k-250115:free',
      'doubao-1-5-pro-256k-250115:free', 'doubao-1-5-pro-32k-250115:free',
      'doubao-1-5-pro-32k-character-250228:free', 'doubao-1-5-thinking-pro-250415:free',
      'doubao-1-5-thinking-vision-pro-250428:free', 'doubao-1-5-vision-pro-32k-250115:free',
      'doubao-1.5-vision-lite-250315:free', 'doubao-1.5-vision-pro-250328:free',
      'doubao-seed-1-6-250615:free', 'doubao-seed-1-6-flash-250615:free',
      'doubao-seed-1-6-thinking-250615:free', 'gemini-2.0-flash:free',
      'gemini-2.0-flash-lite:free', 'gemini-2.5-flash:free', 'gemini-2.5-flash-lite:free',
      'gemini-2.5-pro:free', 'gemini-3-flash-preview:free', 'gemini-3-pro-preview:free',
      'grok-3:free', 'grok-3-beta:free', 'grok-3-mini:free', 'grok-3-mini-beta:free',
      'grok-4:free', 'qwen-long:free', 'qwen-long-2025-01-25:free',
      'qwen-long-latest:free', 'qwen-max:free', 'qwen-max-2025-01-25:free',
      'qwen-max-latest:free', 'qwen-plus:free', 'qwen-plus-2025-04-28:free',
      'qwen-plus-latest:free', 'qwen-turbo:free', 'qwen-turbo-2025-04-28:free',
      'qwen-turbo-latest:free', 'qwen3-0.6b:free', 'qwen3-1.7b:free', 'qwen3-14b:free',
      'qwen3-235b-a22b:free', 'qwen3-235b-a22b-instruct-2507:free',
      'qwen3-30b-a3b:free', 'qwen3-32b:free', 'qwen3-4b:free', 'qwen3-8b:free',
      'qwen3-coder-480b-a35b-instruct:free', 'qwq-plus:free',
      'qwq-plus-2025-03-05:free', 'qwq-plus-latest:free',
    ],
  },
  {
    id: 'meganova', name: 'MegaNova', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://inference.meganova.ai/v1', env: 'MEGANOVA_API_KEY', discover: false,
    signup: 'https://meganova.ai', autoModel: 'meganova-ai/manta-mini-1.0', autoPriority: 28,
    free: 'Tier-1 text models need no credit balance and have per-model daily limits.',
    models: [
      'meganova-ai/manta-mini-1.0', 'meganova-ai/manta-flash-1.0',
      'meganova-ai/manta-pro-1.0', 'deepseek-ai/DeepSeek-V3-0324-Free',
      'Sao10K/L3-8B-Stheno-v3.2', 'Sao10K/L3-70B-Euryale-v2.1',
      'Steelskull/L3.3-MS-Nevoria-70b', 'BruhzWater/Sapphira-L3.3-70b-0.1',
      'FallenMerick/MN-Violet-Lotus-12B', 'mistralai/Mistral-Small-3.2-24B-Instruct-2506',
    ],
  },
  {
    id: 'zylo', name: 'Zylo AI', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.zyloai.net/v1', env: 'ZYLO_API_KEY', publicCatalog: true,
    signup: 'https://zyloai.net', modelPolicy: 'basic-free', chatOnly: true,
    autoModel: 'gpt-oss-20b', autoPriority: 29,
    free: 'Basic plan is card-free; Orb lists only Basic-tier chat models with explicit zero prices.',
    models: [
      'mistral-small-4', 'nemotron-3-ultra', 'gpt-oss-20b', 'qwen-3.5',
      'qwen-3.5-flash', 'mistral-large-3', 'llama-3.2-3b', 'step-3.7',
      'diffusiongemma',
    ],
  },
  {
    id: 'voidai', name: 'VoidAI', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.voidai.app/v1', env: 'VOIDAI_API_KEY', discover: false,
    signup: 'https://voidai.app',
    free: 'Free plan resets 125,000 credits daily; kept out of automatic routing because usage is credit-metered.',
    models: [
      'deepseek-v3.2', 'deepseek-v4-flash', 'deepseek-v4-flash-0731', 'deepseek-v4-pro',
      'glm-5.2', 'gpt-oss-20b', 'kimi-k2.6', 'kimi-k2.7-code', 'kimi-k3',
      'qwen3-coder-480b-a35b-instruct', 'umbra',
    ],
  },
  {
    id: 'poolside', name: 'Poolside', badge: 'FREE PREVIEW', kind: 'cloud', keyless: false,
    baseUrl: 'https://inference.poolside.ai/v1', env: 'POOLSIDE_API_KEY', discover: false,
    signup: 'https://poolside.ai/models',
    free: 'Laguna models are free during the provider’s limited-time public preview.',
    models: ['poolside/laguna-s-2.1', 'poolside/laguna-xs-2.1'],
  },
  {
    id: 'mixlayer', name: 'Mixlayer', badge: 'FREE MODEL', kind: 'community', keyless: false,
    baseUrl: 'https://models.mixlayer.ai/v1', env: 'MIXLAYER_API_KEY', discover: false,
    signup: 'https://mixlayer.ai', modelPolicy: 'free-suffix',
    free: 'The explicit free route is capped by the provider’s free request limits.',
    models: ['qwen/qwen3.5-4b-free'],
  },
  {
    id: 'longcat', name: 'LongCat', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.longcat.chat/openai/v1', env: 'LONGCAT_API_KEY',
    signup: 'https://longcat.chat/platform/',
    free: 'New accounts may receive a one-time evaluation grant; later use is metered.',
    models: ['LongCat-2.0'],
  },
  {
    id: 'reka', name: 'Reka', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.reka.ai/v1', env: 'REKA_API_KEY',
    signup: 'https://platform.reka.ai',
    free: 'Account creation is free, but current chat pricing is pay-as-you-go.',
    models: ['reka-flash', 'reka-edge', 'reka-edge-2603'],
  },
]);

export const PROVIDER_BY_ID = new Map(PROVIDERS.map(provider => [provider.id, provider]));

export function parseRoute(value) {
  const route = String(value || '').trim();
  const slash = route.indexOf('/');
  if (slash < 1) return { providerId: null, model: route };
  const providerId = route.slice(0, slash).toLowerCase();
  return PROVIDER_BY_ID.has(providerId)
    ? { providerId, model: route.slice(slash + 1) }
    : { providerId: null, model: route };
}

export function routeName(providerId, model) {
  return `${providerId}/${model}`;
}
