export const PROVIDERS = Object.freeze([
  {
    id: 'auto', name: 'Orb Auto', badge: 'AUTO', kind: 'virtual', keyless: true,
    baseUrl: '', env: null, signup: '', discover: false,
    free: 'Falls back across ready local and keyless cloud routes.', models: ['free'],
  },
  {
    id: 'ollama', name: 'Ollama', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:11434/v1', modelsUrl: 'http://127.0.0.1:11434/api/tags',
    env: null, signup: 'https://ollama.com/download',
    free: 'Runs on your machine; no account, key, or usage charge.',
    models: ['qwen2.5:1.5b'],
  },
  {
    id: 'llamacpp', name: 'llama.cpp', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/ggml-org/llama.cpp',
    free: 'Runs on your machine; no account, key, or usage charge.', models: [],
  },
  {
    id: 'lmstudio', name: 'LM Studio', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:1234/v1', env: null,
    signup: 'https://lmstudio.ai',
    free: 'Discovers models served by LM Studio on its standard local port.', models: [],
  },
  {
    id: 'vllm', name: 'vLLM', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: null,
    signup: 'https://github.com/vllm-project/vllm',
    free: 'Connects to a local vLLM OpenAI-compatible server.', models: [],
  },
  {
    id: 'friendli-container', name: 'Friendli Container', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: null,
    signup: 'https://friendli.ai/docs/guides/container/quickstart',
    free: 'Connects to a self-hosted Friendli Container on its documented default port.', models: [],
  },
  {
    id: 'fastchat', name: 'FastChat', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: null,
    signup: 'https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md',
    free: 'Connects to FastChat’s self-hosted OpenAI-compatible API server.', models: [],
  },
  {
    id: 'triton-openai', name: 'NVIDIA Triton OpenAI Frontend', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:9000/v1', env: null,
    signup: 'https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/client_guide/openai_readme.html',
    free: 'Discovers models served by Triton’s OpenAI-compatible frontend on port 9000.',
    models: ['tensorrt_llm_bls'],
  },
  {
    id: 'open-webui', name: 'Open WebUI', badge: 'LOCAL', kind: 'local', keyless: false,
    baseUrl: 'http://127.0.0.1:3000/api', env: 'OPEN_WEBUI_API_KEY',
    signup: 'https://docs.openwebui.com/reference/api-endpoints/',
    free: 'Routes through a self-hosted Open WebUI instance and its connected local or cloud models.', models: [],
  },
  {
    id: 'lemonade', name: 'Lemonade Server', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/api/v1', env: null,
    signup: 'https://github.com/lemonade-sdk/lemonade',
    free: 'Runs ONNX models locally through Lemonade’s OpenAI-compatible server.', models: [],
  },
  {
    id: 'bedrock-gateway', name: 'Bedrock Access Gateway', badge: 'SELF HOSTED', kind: 'local', keyless: false,
    baseUrl: 'http://127.0.0.1:8000/api/v1', env: 'BEDROCK_GATEWAY_API_KEY',
    signup: 'https://github.com/aws-samples/bedrock-access-gateway',
    free: 'The gateway is self-hosted; underlying Amazon Bedrock model usage remains metered.', models: [],
  },
  {
    id: 'kubeai', name: 'KubeAI', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8081/openai/v1', env: null,
    signup: 'https://www.kubeai.org',
    free: 'Discovers models served by a local KubeAI Kubernetes installation.', models: [],
  },
  {
    id: 'kong-ai', name: 'Kong AI Gateway', badge: 'SELF HOSTED', kind: 'local', keyless: true,
    baseUrl: '', baseEnv: 'KONG_AI_GATEWAY_BASE_URL', requiresBaseUrl: true,
    env: 'KONG_AI_GATEWAY_KEY', optionalKey: true, signup: 'https://docs.konghq.com/gateway/latest/ai-gateway/',
    free: 'Connects to a configured Kong AI Proxy route; upstream model charges may still apply.', models: [],
  },
  {
    id: 'tyk-ai', name: 'Tyk AI Studio', badge: 'SELF HOSTED', kind: 'local', keyless: false,
    baseUrl: '', baseEnv: 'TYK_AI_STUDIO_BASE_URL', requiresBaseUrl: true,
    env: 'TYK_AI_STUDIO_API_KEY', signup: 'https://tyk.io/docs/ai-management/ai-studio/quickstart',
    free: 'Connects to a Tyk OpenAI-compatible route; upstream model charges depend on its configuration.', models: [],
  },
  {
    id: 'localai', name: 'LocalAI', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/mudler/LocalAI',
    free: 'Connects to a local LocalAI server; override the endpoint if its port differs.', models: [],
  },
  {
    id: 'jan', name: 'Jan', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:1337/v1', env: null,
    signup: 'https://jan.ai',
    free: 'Discovers models exposed by Jan’s local OpenAI-compatible API.', models: [],
  },
  {
    id: 'koboldcpp', name: 'KoboldCpp', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:5001/v1', env: null,
    signup: 'https://github.com/LostRuins/koboldcpp',
    free: 'Connects to KoboldCpp’s local OpenAI-compatible endpoint.', models: [],
  },
  {
    id: 'gpt4all', name: 'GPT4All', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:4891/v1', env: null,
    signup: 'https://github.com/nomic-ai/gpt4all/wiki/Local-API-Server',
    free: 'Discovers models from GPT4All Desktop’s optional local API server.', models: [],
  },
  {
    id: 'textgen', name: 'Text Generation WebUI', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:5000/v1', env: null,
    signup: 'https://github.com/oobabooga/text-generation-webui',
    free: 'Connects to the local OpenAI-compatible API started with `--api`.', models: [],
  },
  {
    id: 'llama-swap', name: 'llama-swap', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/mostlygeek/llama-swap',
    free: 'Discovers locally configured models and starts their backend on demand.', models: [],
  },
  {
    id: 'sglang', name: 'SGLang', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:30000/v1', env: null,
    signup: 'https://github.com/sgl-project/sglang',
    free: 'Connects to SGLang’s local OpenAI-compatible server on its documented port.', models: [],
  },
  {
    id: 'aphrodite', name: 'Aphrodite Engine', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:2242/v1', env: null,
    signup: 'https://github.com/PygmalionAI/aphrodite-engine',
    free: 'Connects to Aphrodite’s local OpenAI-compatible server.', models: [],
  },
  {
    id: 'mlx-lm', name: 'MLX LM', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/ml-explore/mlx-lm',
    free: 'Discovers models served locally by MLX LM on Apple silicon.', models: [],
  },
  {
    id: 'tabbyapi', name: 'TabbyAPI', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:5000/v1', env: 'TABBY_API_KEY', optionalKey: true,
    signup: 'https://github.com/theroyallab/tabbyAPI',
    free: 'Runs locally; set an optional key or explicitly disable TabbyAPI authentication.', models: [],
  },
  {
    id: 'tgi', name: 'Text Generation Inference', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/huggingface/text-generation-inference',
    free: 'Connects to a locally hosted Hugging Face TGI Messages API.', models: [],
  },
  {
    id: 'xinference', name: 'Xinference', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:9997/v1', env: null,
    signup: 'https://github.com/xorbitsai/inference',
    free: 'Discovers models across Xinference’s local unified OpenAI-compatible endpoint.', models: [],
  },
  {
    id: 'mlc-llm', name: 'MLC LLM', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: null,
    signup: 'https://github.com/mlc-ai/mlc-llm',
    free: 'Connects to the local MLC LLM REST server.', models: [],
  },
  {
    id: 'llama-cpp-python', name: 'llama-cpp-python', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: 'LLAMA_CPP_PYTHON_API_KEY', optionalKey: true,
    signup: 'https://github.com/abetlen/llama-cpp-python',
    free: 'Connects to llama-cpp-python’s local OpenAI-compatible server; an optional key is supported.', models: [],
  },
  {
    id: 'transformers-serve', name: 'Transformers Serve', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: null,
    signup: 'https://huggingface.co/docs/transformers/serve-cli/serving',
    free: 'Discovers models from the local OpenAI-compatible Transformers Serve CLI.', models: [],
  },
  {
    id: 'llamafile', name: 'llamafile', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: null,
    signup: 'https://github.com/mozilla-ai/llamafile',
    free: 'Discovers models from a local llamafile server on its default port.', models: [],
  },
  {
    id: 'docker-model-runner', name: 'Docker Model Runner', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:12434/engines/v1', env: null,
    signup: 'https://docs.docker.com/ai/model-runner/',
    free: 'Uses Docker Model Runner’s keyless local OpenAI-compatible API.', models: [],
  },
  {
    id: 'exo', name: 'exo', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:52415/v1', env: null,
    signup: 'https://github.com/exo-explore/exo',
    free: 'Discovers models served by an exo cluster across your own devices.', models: [],
  },
  {
    id: 'privatemode', name: 'Privatemode Proxy', badge: 'LOCAL PROXY', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', env: 'PRIVATEMODE_API_KEY', optionalKey: true,
    signup: 'https://portal.privatemode.ai/',
    free: 'Connects through the local confidential-computing proxy; service usage is account-metered.',
    models: ['kimi-latest', 'gpt-oss-120b'],
  },
  {
    id: 'litellm', name: 'LiteLLM Proxy', badge: 'LOCAL PROXY', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:4000', env: 'LITELLM_MASTER_KEY', optionalKey: true,
    signup: 'https://docs.litellm.ai/docs/proxy/quick_start',
    free: 'Discovers models routed by a local LiteLLM gateway; upstream provider charges still apply.', models: [],
  },
  {
    id: 'nvidia-nim-local', name: 'NVIDIA NIM Local', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: null,
    signup: 'https://docs.nvidia.com/nim/large-language-models/latest/get-started/quickstart.html',
    free: 'Connects to an NVIDIA NIM LLM container on its documented local port.', models: [],
  },
  {
    id: 'ray-serve', name: 'Ray Serve LLM', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', env: 'RAY_SERVE_API_KEY', optionalKey: true,
    signup: 'https://docs.ray.io/en/latest/serve/llm/index.html',
    free: 'Discovers models from a local Ray Serve OpenAI-compatible deployment.', models: [],
  },
  {
    id: 'pollinations', name: 'Pollinations', badge: 'KEYLESS', kind: 'community', keyless: true,
    baseUrl: 'https://text.pollinations.ai/openai', env: 'POLLINATIONS_API_KEY', optionalKey: true,
    signup: 'https://enter.pollinations.ai',
    free: 'Keyless community access is rate-limited; an optional key raises limits.',
    models: ['openai-fast'],
  },
  {
    id: 'github', name: 'GitHub Models', badge: 'FREE RETIRED', kind: 'cloud', keyless: false,
    baseUrl: 'https://models.github.ai/inference', env: 'GITHUB_TOKEN',
    signup: 'https://github.com/marketplace/models',
    free: 'The free tier retired July 30, 2026; kept for accounts that still have API access.',
    models: ['openai/gpt-4.1-mini', 'openai/gpt-4o-mini', 'deepseek/DeepSeek-V3-0324', 'meta/Llama-4-Scout-17B-16E-Instruct'],
  },
  {
    id: 'openrouter', name: 'OpenRouter', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://openrouter.ai/api/v1', env: 'OPENROUTER_API_KEY',
    signup: 'https://openrouter.ai/settings/keys',
    free: 'Models ending in :free have separate rate limits and no token charge.',
    modelPolicy: 'free-suffix',
    models: [
      'openrouter/free', 'deepseek/deepseek-r1-0528:free', 'qwen/qwen3-coder:free',
      'meta-llama/llama-3.3-70b-instruct:free', 'cohere/north-mini-code:free',
      'google/gemma-4-26b-a4b-it:free', 'liquid/lfm-2.5-2.6b:free',
      'nvidia/nemotron-3-nano-30b-a3b:free',
      'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
      'nvidia/nemotron-3-super-120b-a12b:free',
      'nvidia/nemotron-3-ultra-550b-a55b:free', 'nvidia/nemotron-3.5-lightning:free',
      'nvidia/nemotron-nano-12b-v2-vl:free', 'nvidia/nemotron-nano-9b-v2:free',
      'openai/gpt-oss-20b:free', 'poolside/laguna-s-2.1:free',
      'poolside/laguna-xs-2.1:free',
    ],
  },
  {
    id: 'anthropic', name: 'Anthropic', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.anthropic.com/v1', protocol: 'anthropic', env: 'ANTHROPIC_API_KEY',
    signup: 'https://console.anthropic.com/settings/keys',
    free: 'Direct Claude API usage is metered through an Anthropic Console account.',
    models: ['claude-opus-4-1', 'claude-sonnet-4-0', 'claude-3-5-haiku-latest'],
  },
  {
    id: 'openai', name: 'OpenAI', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.openai.com/v1', env: 'OPENAI_API_KEY',
    signup: 'https://platform.openai.com/api-keys',
    free: 'API usage is metered separately from ChatGPT subscriptions.',
    models: ['gpt-5.2', 'gpt-5-mini', 'gpt-4.1'],
  },
  {
    id: 'perplexity', name: 'Perplexity Sonar', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.perplexity.ai', env: 'PERPLEXITY_API_KEY',
    signup: 'https://www.perplexity.ai/settings/api',
    free: 'Sonar API requests are metered through a Perplexity API account.',
    models: ['sonar', 'sonar-pro', 'sonar-reasoning-pro'],
  },
  {
    id: 'venice', name: 'Venice AI', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.venice.ai/api/v1', env: 'VENICE_API_KEY',
    signup: 'https://venice.ai/settings/api',
    free: 'Pay-per-token inference with account-specific balances and promotions.',
    models: ['zai-org-glm-5-1', 'kimi-k2-5', 'qwen3-4b'],
  },
  {
    id: 'scaleway', name: 'Scaleway Generative APIs', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.scaleway.ai/v1', env: 'SCW_SECRET_KEY',
    signup: 'https://console.scaleway.com/generative-api',
    free: 'Serverless inference is metered; availability and introductory allowances vary by account.',
    models: ['glm-5.2', 'gpt-oss-120b'],
  },
  {
    id: 'vultr', name: 'Vultr Serverless Inference', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.vultrinference.com/v1', env: 'VULTR_SERVERLESS_INFERENCE_API_KEY',
    signup: 'https://my.vultr.com/serverless-inference/',
    free: 'Serverless model inference is billed through your Vultr account.', models: [],
  },
  {
    id: 'clarifai', name: 'Clarifai', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.clarifai.com/v2/ext/openai/v1', env: 'CLARIFAI_PAT',
    signup: 'https://clarifai.com/settings/security',
    free: 'Inference consumes Clarifai compute units or account credits.',
    models: ['openai/chat-completion/models/gpt-oss-120b', 'anthropic/completion/models/claude-sonnet-4'],
  },
  {
    id: 'sesterce', name: 'Sesterce Inference', badge: 'CUSTOM', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'SESTERCE_OPENAI_BASE_URL', requiresBaseUrl: true, env: 'SESTERCE_API_KEY',
    signup: 'https://console.sesterce.com/',
    free: 'Connects to your metered OpenAI-compatible inference instance endpoint.', models: [],
  },
  {
    id: 'bentocloud', name: 'BentoCloud', badge: 'CUSTOM', kind: 'cloud', keyless: true,
    baseUrl: '', baseEnv: 'BENTOCLOUD_OPENAI_BASE_URL', requiresBaseUrl: true,
    env: 'BENTOCLOUD_API_KEY', optionalKey: true,
    signup: 'https://cloud.bentoml.com/',
    free: 'Connects to your OpenAI-compatible BentoCloud deployment; deployment charges may apply.', models: [],
  },
  {
    id: 'runpod', name: 'Runpod Serverless', badge: 'CUSTOM', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'RUNPOD_OPENAI_BASE_URL', requiresBaseUrl: true, env: 'RUNPOD_API_KEY',
    signup: 'https://www.runpod.io/console/serverless',
    free: 'Connects to your metered vLLM or SGLang endpoint using its OpenAI-compatible URL.', models: [],
  },
  {
    id: 'infomaniak', name: 'Infomaniak AI Tools', badge: 'CUSTOM', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'INFOMANIAK_AI_BASE_URL', requiresBaseUrl: true, env: 'INFOMANIAK_API_TOKEN',
    signup: 'https://manager.infomaniak.com/',
    free: 'Requires an AI Tools product and its product-specific OpenAI-compatible endpoint.', models: [],
  },
  {
    id: 'together', name: 'Together AI', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.together.xyz/v1', env: 'TOGETHER_API_KEY',
    signup: 'https://api.together.ai/settings/api-keys',
    free: 'Usage is billed by Together AI; account promotions may provide temporary credits.',
    models: ['openai/gpt-oss-20b', 'openai/gpt-oss-120b'],
  },
  {
    id: 'deepinfra', name: 'DeepInfra', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.deepinfra.com/v1/openai', env: 'DEEPINFRA_API_KEY',
    signup: 'https://deepinfra.com/dash/api_keys',
    free: 'Usage is metered; any promotional account credit is separate from Orb.',
    models: ['deepseek-ai/DeepSeek-V4-Flash', 'Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo'],
  },
  {
    id: 'hyperbolic', name: 'Hyperbolic', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.hyperbolic.xyz/v1', env: 'HYPERBOLIC_API_KEY',
    signup: 'https://app.hyperbolic.xyz/settings',
    free: 'Serverless inference is metered; the basic account tier has no minimum deposit.',
    models: ['deepseek-ai/DeepSeek-R1', 'Qwen/Qwen2.5-Coder-32B-Instruct'],
  },
  {
    id: 'aimlapi', name: 'AI/ML API', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.aimlapi.com/v1', env: 'AIMLAPI_KEY',
    signup: 'https://aimlapi.com/app/keys',
    free: 'Usage is metered; available trial or promotional credits are account-specific.',
    models: ['openai/gpt-5-chat-latest', 'openai/o4-mini', 'google/gemma-3-4b-it'],
  },
  {
    id: 'groq', name: 'GroqCloud', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.groq.com/openai/v1', env: 'GROQ_API_KEY',
    signup: 'https://console.groq.com/keys',
    free: 'Developer plan has published per-model rate limits.',
    models: [
      'llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'openai/gpt-oss-20b',
      'openai/gpt-oss-120b', 'qwen/qwen3.6-27b', 'allam-2-7b',
      'groq/compound', 'groq/compound-mini',
    ],
  },
  {
    id: 'cerebras', name: 'Cerebras Inference', badge: 'TRIAL', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.cerebras.ai/v1', env: 'CEREBRAS_API_KEY',
    signup: 'https://cloud.cerebras.ai',
    free: 'Currently trial credit and payment verification, not a permanent card-free tier.',
    models: ['llama3.1-8b', 'gpt-oss-120b', 'qwen-3-32b'],
  },
  {
    id: 'gemini', name: 'Google Gemini', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai', env: 'GEMINI_API_KEY',
    signup: 'https://aistudio.google.com/app/apikey',
    free: 'Google AI Studio offers a rate-limited free tier in supported regions.',
    models: ['gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemma-3-27b-it'],
  },
  {
    id: 'mistral', name: 'Mistral La Plateforme', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.mistral.ai/v1', env: 'MISTRAL_API_KEY',
    signup: 'https://console.mistral.ai/api-keys',
    free: 'Experiment plan is rate-limited and may require account verification.',
    models: [
      'mistral-small-latest', 'open-mistral-nemo', 'codestral-latest',
      'mistral-code-agent-latest', 'devstral-medium-latest', 'magistral-small-latest',
      'mistral-code-fim-latest', 'mistral-code-latest', 'mistral-large-latest',
      'mistral-medium-2604', 'mistral-medium-3', 'mistral-medium-3.5',
      'mistral-medium-latest', 'devstral-latest', 'ministral-14b-latest',
      'ministral-8b-latest', 'ministral-3b-latest', 'mistral-medium-2505',
      'mistral-medium-2508', 'mistral-vibe-cli-fast', 'mistral-vibe-cli-latest',
      'mistral-vibe-cli-with-tools', 'voxtral-small-latest', 'glm-5-2',
    ],
  },
  {
    id: 'nvidia', name: 'NVIDIA NIM', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://integrate.api.nvidia.com/v1', env: 'NVIDIA_API_KEY',
    signup: 'https://build.nvidia.com',
    free: 'Developer API access includes a limited evaluation allowance.',
    models: [
      'meta/llama-3.1-8b-instruct', 'deepseek-ai/deepseek-r1',
      'qwen/qwen3-coder-480b-a35b-instruct', 'deepseek-ai/deepseek-v4-flash-0731',
      'meta/llama-3.1-70b-instruct', 'meta/llama-3.2-11b-vision-instruct',
      'meta/llama-3.2-3b-instruct', 'nvidia/llama-3.3-nemotron-super-49b-v1',
      'nvidia/llama-3.3-nemotron-super-49b-v1.5',
      'nvidia/nemotron-3-nano-30b-a3b',
      'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning',
      'nvidia/nemotron-3-super-120b-a12b', 'nvidia/nemotron-3-ultra-550b-a55b',
      'nvidia/nemotron-nano-12b-v2-vl', 'nvidia/nvidia-nemotron-nano-9b-v2',
      'openai/gpt-oss-120b', 'openai/gpt-oss-20b', 'poolside/laguna-xs-2.1',
      'stepfun-ai/step-3.7-flash', 'thinkingmachines/inkling',
    ],
  },
  {
    id: 'sambanova', name: 'SambaNova Cloud', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.sambanova.ai/v1', env: 'SAMBANOVA_API_KEY',
    signup: 'https://cloud.sambanova.ai/apis',
    free: 'Free developer access is rate-limited.',
    models: ['Meta-Llama-3.3-70B-Instruct', 'DeepSeek-R1', 'DeepSeek-V3.1', 'Qwen3-32B'],
  },
  {
    id: 'huggingface', name: 'Hugging Face Inference', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://router.huggingface.co/v1', env: 'HF_TOKEN',
    signup: 'https://huggingface.co/settings/tokens',
    free: 'Free accounts receive a small monthly inference allowance.',
    models: ['meta-llama/Llama-3.1-8B-Instruct', 'Qwen/Qwen2.5-Coder-32B-Instruct', 'deepseek-ai/DeepSeek-R1:fastest'],
  },
  {
    id: 'siliconflow', name: 'SiliconFlow', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.siliconflow.com/v1', env: 'SILICONFLOW_API_KEY',
    signup: 'https://cloud.siliconflow.com/account/ak',
    free: 'New accounts may receive promotional balance; terms can change.',
    models: ['Qwen/Qwen2.5-7B-Instruct', 'deepseek-ai/DeepSeek-V3', 'THUDM/GLM-4-9B-0414'],
  },
  {
    id: 'chutes', name: 'Chutes', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://llm.chutes.ai/v1', env: 'CHUTES_API_KEY',
    signup: 'https://chutes.ai',
    free: 'Current public inference is pay-per-token; retained as an optional direct provider.',
    models: ['deepseek-ai/DeepSeek-V3-0324', 'Qwen/Qwen3-32B', 'unsloth/gemma-3-27b-it'],
  },
  {
    id: 'cohere', name: 'Cohere', badge: 'FREE EVAL', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.cohere.ai/compatibility/v1', env: 'COHERE_API_KEY',
    signup: 'https://dashboard.cohere.com/api-keys',
    free: 'Evaluation keys are free, limited to 1,000 calls/month and per-model RPM limits.',
    models: [
      'command-a-plus-05-2026', 'command-a-03-2025', 'command-r-plus',
      'command-r7b-12-2024', 'c4ai-aya-vision-32b', 'command-a-vision-07-2025',
      'command-r-08-2024', 'command-r-plus-08-2024', 'command-r7b-arabic-02-2025',
      'c4ai-aya-expanse-32b', 'command-a-reasoning-08-2025',
      'command-a-translate-08-2025',
    ],
  },
  {
    id: 'cloudflare', name: 'Cloudflare Workers AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'CLOUDFLARE_AI_BASE_URL', requiresBaseUrl: true, env: 'CLOUDFLARE_API_TOKEN',
    signup: 'https://dash.cloudflare.com/profile/api-tokens',
    free: 'Daily Workers AI allocation; set the account-specific OpenAI endpoint with `orb endpoint set cloudflare`.',
    models: [
      '@cf/meta/llama-3.3-70b-instruct-fp8-fast', '@cf/openai/gpt-oss-120b',
      '@cf/qwen/qwen2.5-coder-32b-instruct', '@cf/aisingapore/gemma-sea-lion-v4-27b-it',
      '@cf/google/gemma-2b-it-lora', '@cf/google/gemma-4-26b-a4b-it',
      '@cf/meta/llama-3.2-1b-instruct', '@cf/meta/llama-3.2-3b-instruct',
      '@cf/meta/llama-4-scout-17b-16e-instruct', '@cf/mistral/mistral-7b-instruct-v0.2-lora',
      '@cf/mistralai/mistral-small-3.1-24b-instruct', '@cf/nvidia/nemotron-3-120b-a12b',
      '@cf/openai/gpt-oss-20b', '@cf/qwen/qwen3-30b-a3b-fp8',
      '@cf/zai-org/glm-4.7-flash', '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b',
      '@cf/google/gemma-7b-it-lora', '@cf/ibm-granite/granite-4.0-h-micro',
      '@cf/meta-llama/llama-2-7b-chat-hf-lora', '@cf/meta-llama/llama-3.1-8b-instruct-fp8',
      '@cf/meta-llama/llama-3.2-11b-vision-instruct', '@cf/qwen/qwq-32b',
    ],
  },
  {
    id: 'fireworks', name: 'Fireworks AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.fireworks.ai/inference/v1', env: 'FIREWORKS_API_KEY',
    signup: 'https://app.fireworks.ai/settings/users/api-keys',
    free: 'Selected access without a payment method is account-wide rate-limited.',
    models: ['accounts/fireworks/models/llama-v3p3-70b-instruct', 'accounts/fireworks/models/gpt-oss-120b'],
  },
  {
    id: 'zai', name: 'Z.AI Open Platform', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.z.ai/api/paas/v4', env: 'ZAI_API_KEY',
    signup: 'https://z.ai/manage-apikey/apikey-list',
    free: 'Flash model input, output, and cache pricing is published as free.',
    models: ['glm-4.7-flash', 'glm-4.5-flash', 'glm-4.6v-flash'],
  },
  {
    id: 'novita', name: 'Novita AI', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.novita.ai/openai', env: 'NOVITA_API_KEY',
    signup: 'https://novita.ai/settings/key-management',
    free: 'Selected models are priced at zero; provider does not publish one global quota.',
    models: ['inclusionai/Ling-3.0-flash', 'moonshotai/kimi-k2-instruct-0905'],
  },
  {
    id: 'dashscope', name: 'Alibaba Model Studio', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://dashscope-us.aliyuncs.com/compatible-mode/v1', env: 'DASHSCOPE_API_KEY',
    signup: 'https://bailian.console.alibabacloud.com/',
    free: 'Model-dependent free quotas; endpoint and key must belong to the same region.',
    models: ['qwen3.6-flash', 'qwen-plus', 'qwen-turbo', 'qwen3-coder-plus'],
  },
  {
    id: 'moonshot', name: 'Moonshot AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.moonshot.ai/v1', env: 'MOONSHOT_API_KEY',
    signup: 'https://platform.moonshot.ai/console/api-keys',
    free: 'Model-dependent account quota; no card required by the reviewed provider list.',
    models: ['kimi-k2-0905-preview', 'moonshot-v1-8k', 'moonshot-v1-128k'],
  },
  {
    id: 'deepseek', name: 'DeepSeek', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.deepseek.com/v1', env: 'DEEPSEEK_API_KEY',
    signup: 'https://platform.deepseek.com/api_keys',
    free: 'Current direct API usage is metered; granted account balance may apply.',
    models: ['deepseek-v4-flash', 'deepseek-v4-pro'],
  },
  {
    id: 'stepfun', name: 'StepFun', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.stepfun.ai/v1', env: 'STEPFUN_API_KEY',
    signup: 'https://platform.stepfun.ai/interface-key',
    free: 'Usage is metered through the StepFun Open Platform.',
    models: ['step-3.5-flash', 'step-3.5-flash-2603'],
  },
  {
    id: 'minimax', name: 'MiniMax', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.minimax.io/v1', env: 'MINIMAX_API_KEY',
    signup: 'https://platform.minimax.io/user-center/basic-information/interface-key',
    free: 'International API and token-plan usage is metered through MiniMax.',
    models: ['MiniMax-M2.7', 'MiniMax-M2.7-highspeed'],
  },
  {
    id: 'baichuan', name: 'Baichuan AI', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.baichuan-ai.com/v1', env: 'BAICHUAN_API_KEY',
    signup: 'https://platform.baichuan-ai.com/console/apikey',
    free: 'Model API usage is metered through the Baichuan platform.',
    models: ['Baichuan2-Turbo'],
  },
  {
    id: 'hunyuan', name: 'Tencent Hunyuan', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1', env: 'HUNYUAN_API_KEY',
    signup: 'https://console.cloud.tencent.com/hunyuan/start',
    free: 'OpenAI-compatible Hunyuan API usage is billed by Tencent Cloud.', models: [],
  },
  {
    id: 'upstage', name: 'Upstage', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.upstage.ai/v1', env: 'UPSTAGE_API_KEY',
    signup: 'https://console.upstage.ai/api-keys',
    free: 'Solar model usage is metered through the Upstage Console.', models: ['solar-pro3'],
  },
  {
    id: 'snowflake', name: 'Snowflake Cortex', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'SNOWFLAKE_CORTEX_BASE_URL', requiresBaseUrl: true,
    env: 'SNOWFLAKE_PAT', signup: 'https://docs.snowflake.com/en/user-guide/snowflake-cortex/cortex-rest-api',
    free: 'Uses Snowflake credits; set the account-specific Cortex `/api/v2/cortex/v1` endpoint.',
    models: ['claude-sonnet-4-5', 'openai-gpt-5'],
  },
  {
    id: 'databricks', name: 'Databricks Model Serving', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'DATABRICKS_SERVING_BASE_URL', requiresBaseUrl: true,
    env: 'DATABRICKS_TOKEN', signup: 'https://docs.databricks.com/en/machine-learning/model-serving/score-foundation-models',
    free: 'Uses workspace billing; set the OpenAI-compatible workspace `/serving-endpoints` base URL.', models: [],
  },
  {
    id: 'friendli', name: 'FriendliAI Serverless', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.friendli.ai/serverless/v1', env: 'FRIENDLI_API_KEY',
    signup: 'https://suite.friendli.ai/personal-settings/tokens',
    free: 'Serverless model usage is metered through Friendli Suite.',
    models: ['meta-llama-3.3-70b-instruct', 'MiniMaxAI/MiniMax-M2.5'],
  },
  {
    id: 'digitalocean', name: 'DigitalOcean Inference', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://inference.do-ai.run/v1', env: 'DIGITALOCEAN_INFERENCE_KEY',
    signup: 'https://cloud.digitalocean.com/gen-ai/model-access-keys',
    free: 'Serverless inference is prepaid and billed per model token usage.',
    models: ['openai-gpt-5.6-sol', 'openai-gpt-5.6-terra', 'openai-gpt-5.6-luna'],
  },
  {
    id: 'digitalocean-agent', name: 'DigitalOcean Agent', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'DIGITALOCEAN_AGENT_BASE_URL', requiresBaseUrl: true,
    env: 'DIGITALOCEAN_AGENT_ACCESS_KEY', signup: 'https://docs.digitalocean.com/products/ai-platform/how-to/use-agents/',
    free: 'Uses the deployed agent and its attached model resources; set the endpoint’s `/api/v1` base URL.',
    models: ['n/a'],
  },
  {
    id: 'heroku', name: 'Heroku Managed Inference', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'HEROKU_INFERENCE_BASE_URL', requiresBaseUrl: true,
    env: 'HEROKU_INFERENCE_KEY', signup: 'https://elements.heroku.com/addons/heroku-inference',
    free: 'Uses the attached Heroku add-on plan; set the provisioned `INFERENCE_URL` with `/v1` appended.',
    models: ['claude-opus-4-5', 'claude-4-5-sonnet', 'claude-4-5-haiku', 'qwen3-coder-480b', 'gpt-oss-120b'],
  },
  {
    id: 'gmi', name: 'GMI Cloud', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.gmi-serving.com/v1', env: 'GMI_API_KEY',
    signup: 'https://console.gmicloud.ai',
    free: 'Inference Engine usage is metered through the GMI Cloud organization.',
    models: ['deepseek-ai/DeepSeek-R1'],
  },
  {
    id: 'modal', name: 'Modal Endpoint', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'MODAL_ENDPOINT_BASE_URL', requiresBaseUrl: true,
    env: 'MODAL_PROXY_TOKEN', signup: 'https://modal.com/docs/guide/endpoints',
    free: 'Compute is usage-billed; set the deployed endpoint `/v1` URL and combined proxy token.', models: [],
  },
  {
    id: 'baseten', name: 'Baseten Model APIs', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://inference.baseten.co/v1', env: 'BASETEN_API_KEY',
    signup: 'https://app.baseten.co/settings/api_keys',
    free: 'Managed model API usage is metered through the Baseten workspace.',
    models: ['deepseek-ai/DeepSeek-V4-Pro', 'zai-org/GLM-5'],
  },
  {
    id: 'coreweave', name: 'CoreWeave Inference', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'COREWEAVE_INFERENCE_BASE_URL', requiresBaseUrl: true,
    env: 'COREWEAVE_API_TOKEN', signup: 'https://console.coreweave.com',
    free: 'Uses provisioned inference capacity; set the OpenAI-compatible gateway base URL.', models: [],
  },
  {
    id: 'requesty', name: 'Requesty', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://router.requesty.ai/v1', env: 'REQUESTY_API_KEY',
    signup: 'https://app.requesty.ai',
    free: 'Unified routing usage is billed through Requesty or connected provider accounts.',
    models: ['openai/gpt-4.1-mini', 'anthropic/claude-sonnet-4-20250514'],
  },
  {
    id: 'helicone', name: 'Helicone AI Gateway', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://ai-gateway.helicone.ai/v1', env: 'HELICONE_API_KEY',
    signup: 'https://us.helicone.ai/settings/api-keys',
    free: 'Gateway billing passes through provider prices with no model markup; account credits are required.',
    models: ['gpt-4o-mini', 'claude-sonnet-4-5/anthropic'],
  },
  {
    id: 'portkey', name: 'Portkey AI Gateway', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.portkey.ai/v1', env: 'PORTKEY_API_KEY',
    signup: 'https://app.portkey.ai/api-keys',
    free: 'Gateway and upstream model charges depend on the connected provider and workspace plan.', models: [],
  },
  {
    id: 'bedrock', name: 'Amazon Bedrock Mantle', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'BEDROCK_MANTLE_BASE_URL', requiresBaseUrl: true,
    env: 'AWS_BEARER_TOKEN_BEDROCK', signup: 'https://console.aws.amazon.com/bedrock/home#/api-keys',
    free: 'Amazon Bedrock usage is metered; set the regional `bedrock-mantle` `/v1` base URL.',
    models: ['openai.gpt-oss-120b', 'us.anthropic.claude-sonnet-4-6'],
  },
  {
    id: 'oci', name: 'OCI Generative AI', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'OCI_GENERATIVE_AI_BASE_URL', requiresBaseUrl: true,
    env: 'OCI_GENERATIVE_AI_API_KEY', signup: 'https://cloud.oracle.com/generative-ai',
    free: 'OCI usage is metered; set the regional OpenAI-compatible `/openai/v1` base URL.',
    models: ['xai.grok-4', 'openai.gpt-oss-120b'],
  },
  {
    id: 'ibm-inference', name: 'IBM Cloud Inference', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'IBM_INFERENCE_BASE_URL', requiresBaseUrl: true,
    env: 'IBM_INFERENCE_BEARER_TOKEN', signup: 'https://cloud.ibm.com/catalog/services/inference',
    free: 'Project inference is metered; set the regional project-specific `/inference` base URL.',
    models: ['granite-4-0-h-small'],
  },
  {
    id: 'azure-foundry', name: 'Microsoft Foundry', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'AZURE_FOUNDRY_BASE_URL', requiresBaseUrl: true,
    env: 'AZURE_FOUNDRY_API_KEY', signup: 'https://ai.azure.com',
    free: 'Deployment usage is metered; set the resource’s OpenAI-compatible `/openai/v1` base URL.', models: [],
  },
  {
    id: 'anyscale', name: 'Anyscale Service', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'ANYSCALE_SERVICE_BASE_URL', requiresBaseUrl: true,
    env: 'ANYSCALE_SERVICE_TOKEN', signup: 'https://console.anyscale.com',
    free: 'Managed Ray Serve compute is usage-billed; set the deployed service `/v1` base URL.', models: [],
  },
  {
    id: 'beam', name: 'Beam Cloud', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'BEAM_OPENAI_BASE_URL', requiresBaseUrl: true,
    env: 'BEAM_API_KEY', signup: 'https://platform.beam.cloud',
    free: 'Serverless GPU compute is usage-billed; set the deployed vLLM or SGLang `/v1` URL.',
    models: ['Qwen/Qwen2.5-7B-Instruct'],
  },
  {
    id: 'cerebrium', name: 'Cerebrium Deployment', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'CEREBRIUM_OPENAI_BASE_URL', requiresBaseUrl: true,
    env: 'CEREBRIUM_API_KEY', signup: 'https://dashboard.cerebrium.ai',
    free: 'Serverless compute is usage-billed; set the OpenAI-compatible deployment base URL.', models: [],
  },
  {
    id: 'crusoe', name: 'Crusoe Managed Inference', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.inference.crusoecloud.com/v1', env: 'CRUSOE_INFERENCE_API_KEY',
    signup: 'https://console.crusoecloud.com',
    free: 'Serverless or reserved inference usage is billed through Crusoe Intelligence Foundry.', models: [],
  },
  {
    id: 'cloudru', name: 'Cloud.ru Foundation Models', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://foundation-models.api.cloud.ru/v1', env: 'CLOUDRU_API_KEY',
    signup: 'https://console.cloud.ru',
    free: 'Foundation Models usage is token-metered through Cloud.ru Evolution.',
    models: ['deepseek-ai/DeepSeek-V4-Pro', 'zai-org/GLM-5.1', 'moonshotai/Kimi-K2.6'],
  },
  {
    id: 'yandex', name: 'Yandex AI Studio', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://ai.api.cloud.yandex.net/v1', env: 'YANDEX_AI_STUDIO_API_KEY',
    signup: 'https://console.yandex.cloud/folders',
    free: 'AI Studio usage is metered; model URIs include the account folder ID.', models: [],
  },
  {
    id: 'volcengine', name: 'Volcano Engine ModelArk', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3', env: 'VOLCENGINE_ARK_API_KEY',
    signup: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apikey',
    free: 'ModelArk usage is metered through Volcano Engine.',
    models: ['doubao-seed-2-0-lite-260215', 'doubao-seed-1-6-251015'],
  },
  {
    id: 'dstack', name: 'dstack Service', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'DSTACK_OPENAI_BASE_URL', requiresBaseUrl: true,
    env: 'DSTACK_SERVICE_TOKEN', signup: 'https://dstack.ai/docs/services/',
    free: 'Compute charges depend on the configured backend; set the service’s OpenAI-compatible base URL.', models: [],
  },
  {
    id: 'pai-eas', name: 'Alibaba PAI-EAS', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'PAI_EAS_BASE_URL', requiresBaseUrl: true,
    env: 'PAI_EAS_TOKEN', signup: 'https://pai.console.aliyun.com',
    free: 'Deployed EAS compute is usage-billed; set the service endpoint with `/v1` appended.',
    models: ['default'],
  },
  {
    id: 'huawei-modelarts', name: 'Huawei ModelArts Studio', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.modelarts-maas.com/v1', env: 'HUAWEI_MODELARTS_API_KEY',
    signup: 'https://console.huaweicloud.com/modelarts/',
    free: 'ModelArts MaaS usage is metered through Huawei Cloud.', models: ['DeepSeek-V31'],
  },
  {
    id: 'ionos', name: 'IONOS AI Model Hub', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://openai.inference.de-txl.ionos.com/v1', env: 'IONOS_AI_MODEL_HUB_TOKEN',
    signup: 'https://dcd.ionos.com',
    free: 'Model Hub usage is token-metered through IONOS Cloud.',
    models: ['openai/gpt-oss-120b', 'meta-llama/Meta-Llama-3.1-8B-Instruct'],
  },
  {
    id: 'stackit', name: 'STACKIT AI Model Serving', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1', env: 'STACKIT_MODEL_SERVING_TOKEN',
    signup: 'https://portal.stackit.cloud',
    free: 'Shared model usage is metered through the STACKIT project.',
    models: ['openai/gpt-oss-120b', 'cortecs/Llama-3.3-70B-Instruct-FP8-Dynamic'],
  },
  {
    id: 'modelscope', name: 'ModelScope', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api-inference.modelscope.cn/v1', env: 'MODELSCOPE_SDK_TOKEN',
    signup: 'https://modelscope.cn/my/myaccesstoken',
    free: 'Selected hosted open models share a daily free request allowance.',
    models: ['MiniMax/MiniMax-M2.5', 'inclusionAI/Ling-2.6-1T', 'deepseek-ai/DeepSeek-V4-Flash', 'ZhipuAI/GLM-5', 'Qwen/Qwen3-Coder-480B-A35B-Instruct'],
  },
  {
    id: 'ollama-cloud', name: 'Ollama Cloud', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://ollama.com/api', modelsUrl: 'https://ollama.com/api/tags', protocol: 'ollama', env: 'OLLAMA_API_KEY',
    signup: 'https://ollama.com/settings/keys',
    free: 'Account cloud models use session and weekly free-plan limits.',
    models: [
      'gpt-oss:120b', 'gpt-oss:20b', 'qwen3-coder:480b', 'deepseek-v3.1:671b',
      'minimax-m2.5', 'gemma4:31b', 'minimax-m3', 'nemotron-3-nano:30b',
      'nemotron-3-super', 'nemotron-3-ultra',
    ],
  },
  {
    id: 'llm7', name: 'LLM7', badge: 'KEYLESS', kind: 'community', keyless: true,
    baseUrl: 'https://api.llm7.io/v1', env: 'LLM7_API_KEY', optionalKey: true,
    signup: 'https://token.llm7.io', modelPolicy: 'included-tier',
    free: 'Anonymous quota works without a key; a free token increases the request limit.',
    models: ['gpt-oss:20b', 'codestral-latest', 'gemini-3.1-flash-lite', 'minimax-m2.7', 'mistral-Nemo-Instruct-2407'],
  },
  {
    id: 'ovh', name: 'OVHcloud AI Endpoints', badge: 'KEYLESS', kind: 'cloud', keyless: true,
    baseUrl: 'https://oai.endpoints.kepler.ai.cloud.ovh.net/v1', env: 'OVH_AI_ENDPOINTS_ACCESS_TOKEN', optionalKey: true,
    signup: 'https://www.ovhcloud.com/en/public-cloud/ai-endpoints/catalog/', chatOnly: true,
    free: 'Anonymous inference is limited to roughly 2 RPM; a token provides account limits.',
    models: ['Qwen3.5-397B-A17B', 'Qwen3.6-27B', 'Meta-Llama-3_3-70B-Instruct', 'gpt-oss-120b', 'gpt-oss-20b', 'Qwen3-Coder-30B-A3B-Instruct'],
  },
  {
    id: 'kilo', name: 'Kilo Gateway', badge: 'KEYLESS', kind: 'community', keyless: true,
    baseUrl: 'https://api.kilo.ai/api/gateway', env: 'KILO_API_KEY', optionalKey: true,
    signup: 'https://kilo.ai', modelPolicy: 'free-suffix',
    free: 'Free-suffixed models allow anonymous access, currently limited per IP.',
    models: [
      'stepfun/step-3.7-flash:free', 'poolside/laguna-s-2.1:free',
      'poolside/laguna-xs-2.1:free', 'tencent/hy3:free',
      'nvidia/nemotron-3-ultra-550b-a55b:free',
      'nvidia/nemotron-3-super-120b-a12b:free',
      'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
      'nvidia/nemotron-3.5-lightning:free', 'cohere/north-mini-code:free',
      'openrouter/free',
    ],
  },
  {
    id: 'opencode', name: 'OpenCode Free Gateway', badge: 'KEYLESS', kind: 'community', keyless: true,
    baseUrl: 'https://console.opencode.ai/inference/openai/v1', env: 'OPENCODE_API_KEY', optionalKey: true,
    signup: 'https://console.opencode.ai', discover: false,
    free: 'The provider documents no-key access for its current free chat models.',
    models: ['big-pickle', 'deepseek-v4-flash-free', 'mimo-v2.5-free', 'nemotron-3-ultra-free', 'north-mini-code-free', 'laguna-s-2.1-free', 'ling-3.0-flash-free'],
  },
  {
    id: 'aion', name: 'Aion Labs', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.aionlabs.ai/v1', env: 'AIONLABS_API_KEY',
    signup: 'https://www.aionlabs.ai',
    free: 'Free account inference is limited by requests and daily tokens.',
    models: [
      'aion-2-5', 'aion-2-0', 'aion-rp-1-0-8b', 'aion-labs/aion-3.0',
      'aion-labs/aion-3.0-mini', 'aion-labs/aion-2.0',
      'aion-labs/aion-rp-llama-3.1-8b',
    ],
  },
  {
    id: 'agnes', name: 'Agnes AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://apihub.agnes-ai.com/v1', env: 'AGNES_API_KEY',
    signup: 'https://platform.agnes-ai.com/settings/apiKeys',
    free: 'Free account models have provider-published per-minute limits.',
    models: ['agnes-1.5-flash', 'agnes-2.0-flash', 'agnes-2.5-flash', 'agnes-2.5-pro', 'agnes-2.5-pro-alpha'],
  },
  {
    id: 'glhf', name: 'GLHF.chat', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://glhf.chat/api/openai/v1', env: 'GLHF_API_KEY',
    signup: 'https://glhf.chat/',
    free: 'Community-hosted free model routes are advertised without a token quota.',
    models: ['meta-llama/Meta-Llama-3.1-70B-Instruct', 'mistralai/Mixtral-8x7B-Instruct-v0.1'],
  },
  {
    id: 'ai21', name: 'AI21 Labs', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.ai21.com/studio/v1', env: 'AI21_API_KEY',
    signup: 'https://studio.ai21.com/account/api-key',
    free: 'Free developer access is limited to the supported Jamba models.',
    models: ['jamba-large-2', 'jamba-mini-2'],
  },
  {
    id: 'nscale', name: 'Nscale', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://inference.api.nscale.com/v1', env: 'NSCALE_API_KEY',
    signup: 'https://console.nscale.com/',
    free: 'Free inference is subject to the provider fair-use policy.',
    models: ['llama-3-3-70b-instruct', 'deepseek-r1-distill-llama-70b'],
  },
  {
    id: 'nebius', name: 'Nebius AI Studio', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.studio.nebius.com/v1', env: 'NEBIUS_API_KEY',
    signup: 'https://studio.nebius.com/settings/api-keys',
    free: 'New-account or renewable credits are tier-dependent; usage may become paid.',
    models: ['Qwen/Qwen3-235B-A22B', 'deepseek-ai/DeepSeek-V3-0324', 'meta-llama/Llama-3.3-70B-Instruct'],
  },
  {
    id: 'xai', name: 'xAI', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.x.ai/v1', env: 'XAI_API_KEY',
    signup: 'https://console.x.ai',
    free: 'Account credits and eligibility vary; the direct API is not universally zero-cost.',
    models: ['grok-3-mini', 'grok-3', 'grok-4-fast-non-reasoning'],
  },
  {
    id: 'vercel', name: 'Vercel AI Gateway', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://ai-gateway.vercel.sh/v1', env: 'VERCEL_AI_GATEWAY_API_KEY',
    signup: 'https://vercel.com/dashboard/ai-gateway',
    free: 'Team accounts receive $5/month until they purchase paid gateway credits.',
    models: ['openai/gpt-oss-120b', 'moonshotai/kimi-k2', 'google/gemini-2.5-flash-lite', 'meta/llama-3.3-70b-instruct'],
  },
  {
    id: 'gonka', name: 'Gonka Broker', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://proxy.gonkabroker.com/v1', env: 'GONKA_API_KEY', publicCatalog: true,
    signup: 'https://app.gonkabroker.com/signup', chatOnly: true,
    free: 'At least one million tokens across any model renew monthly; no card is required.',
    models: [
      'MiniMaxAI/MiniMax-M2.7', 'deepseek-ai/DeepSeek-V4-Flash-0731',
      'moonshotai/Kimi-K2.6',
    ],
  },
  {
    id: 'airforce', name: 'Api.Airforce', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.airforce/v1', env: 'AIRFORCE_API_KEY', publicCatalog: true,
    signup: 'https://api.airforce/', modelPolicy: 'free-tier', chatOnly: true,
    autoModel: 'gemma3-270m:free', autoPriority: 40,
    free: 'Free plan has 1 RPM and 1,000 RPD; Orb lists only explicit zero-cost routes.',
    models: ['gemma3-270m:free'],
  },
  {
    id: 'bazaarlink', name: 'BazaarLink', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://bazaarlink.ai/api/v1', env: 'BAZAARLINK_API_KEY', publicCatalog: true,
    signup: 'https://bazaarlink.ai', modelPolicy: 'free-suffix',
    autoModel: 'auto:free', autoPriority: 30,
    headers: { 'x-free-fallback': 'false' },
    free: 'Free models have per-model daily quotas; Orb disables fallback into paid usage.',
    models: ['auto:free', 'deepseek/deepseek-v4-flash:free', 'qwen/qwen3.7-flash:free'],
  },
  {
    id: 'literouter', name: 'LiteRouter', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.literouter.com/v1', env: 'LITEROUTER_API_KEY',
    signup: 'https://literouter.com', modelPolicy: 'free-suffix',
    autoModel: 'gpt-oss-120b:free', autoPriority: 10,
    free: 'Free-suffixed routes have a seven-second cooldown and no token price.',
    models: [
      'claude-haiku-4.5-cheap:free', 'deepseek-r1-0528:free', 'deepseek-r1:free',
      'deepseek-reasoner:free', 'deepseek-v3-0324:free', 'deepseek-v3.1-terminus:free',
      'deepseek-v3.1:free', 'deepseek-v3.2:free', 'deepseek-v3:free',
      'gemini-2.5-flash-lite:free', 'gemini-2.5-flash:free', 'gemma-3-27b-it:free',
      'gemma-4-31b:free', 'gpt-4.1-mini:free', 'gpt-4.1-nano:free', 'gpt-4o-mini:free',
      'gpt-5-nano:free', 'gpt-oss-120b:free', 'gpt-oss-20b:free',
      'grok-4.1-fast-reasoning:free', 'l3-8b-lunaris:free', 'llama-3-8b-instruct:free',
      'llama-3.1-8b-instruct:free', 'llama-3.3-70b-instruct-turbo:free',
      'minimax-m2.7:free', 'ministral-3b-2512:free', 'mistral-large-3:free',
      'mistral-nemo-instruct-2407:free', 'mistral-small-24b-instruct-2501:free',
      'mythomax-l2-13b:free', 'nemotron-3-nano:free', 'openrouter:free', 'qwen3.5:free',
    ],
  },
  {
    id: 'llm-kiwi', name: 'LLM.kiwi', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://api.llm.kiwi/v1', env: 'LLM_KIWI_API_KEY', publicCatalog: true,
    signup: 'https://llm.kiwi',
    free: 'Free account requires no card and provides a rate-limited `auto` route.',
    models: ['auto'],
  },
  {
    id: 'publicai', name: 'Public AI Gateway', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://api.publicai.co/v1', env: 'PUBLICAI_API_KEY',
    signup: 'https://platform.publicai.co',
    autoModel: 'swiss-ai/apertus-70b-instruct', autoPriority: 20,
    headers: { 'user-agent': 'orb-route/0.11.0' },
    free: 'Public-interest inference tier with a provider-published request limit.',
    models: ['swiss-ai/apertus-70b-instruct', 'swiss-ai/Apertus-8B-Instruct-2509', 'aisingapore/Qwen-SEA-LION-v4-32B-IT', 'aisingapore/Gemma-SEA-LION-v4-27B-IT', 'allenai/Olmo-3-32B-Think', 'allenai/Olmo-3-7B-Instruct', 'utter-project/EuroLLM-22B-Instruct-2512'],
  },
  {
    id: 'morph', name: 'Morph', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.morphllm.com/v1', env: 'MORPH_API_KEY',
    signup: 'https://www.morphllm.com',
    free: 'Free allowance includes 200 requests each month; further usage is metered.',
    models: ['morph-v3-large', 'morph-v3-fast', 'morph-glm52-744b', 'morph-qwen35-397b', 'morph-qwen36-27b', 'morph-minimax3-428b', 'morph-dsv4flash'],
  },
  {
    id: 'ant-ling', name: 'Ant Ling', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.ant-ling.com/v1', env: 'ANT_LING_API_KEY',
    signup: 'https://developer.ant-ling.com/en/docs/getting-started/quickstart/',
    free: 'Account allowance resets at 500,000 tokens/day; paid overage requires billing setup.',
    models: ['Ling-3.0-flash', 'Ling-2.6-1T', 'Ling-2.6-flash', 'Ring-2.6-1T'],
  },
  {
    id: 'anyapi', name: 'AnyAPI AI', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.anyapi.ai/v1', env: 'ANYAPI_API_KEY',
    signup: 'https://anyapi.ai', modelPolicy: 'free-suffix',
    autoModel: 'nvidia/nemotron-3-nano-30b-a3b:free', autoPriority: 12,
    free: 'Free plan includes 100,000 anyTokens per day; Orb routes only explicit :free models.',
    models: [
      'google/gemma-4-26b-a4b-it:free', 'nvidia/nemotron-3-nano-30b-a3b:free',
      'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
      'nvidia/nemotron-3-ultra-550b-a55b:free', 'nvidia/nemotron-nano-12b-v2-vl:free',
      'nvidia/nemotron-nano-9b-v2:free',
    ],
  },
  {
    id: 'fastrouter', name: 'FastRouter', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.fastrouter.ai/api/v1', env: 'FASTROUTER_API_KEY', publicCatalog: true,
    signup: 'https://fastrouter.ai', modelPolicy: 'free-suffix', chatOnly: true,
    autoModel: 'openai/gpt-oss-120b:free', autoPriority: 14,
    free: 'Free-suffixed models have zero token pricing and small daily request limits.',
    models: [
      'openai/gpt-oss-120b:free', 'openai/gpt-oss-20b:free', 'google/gemma4-26b:free',
      'nvidia/nemotron-3-nano-30b:free', 'nvidia/nemotron-3-super:free',
      'sarvam/sarvam-105b:free',
    ],
  },
  {
    id: 'routeway', name: 'Routeway', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.routeway.ai/v1', env: 'ROUTEWAY_API_KEY', publicCatalog: true,
    signup: 'https://routeway.ai', modelPolicy: 'free-suffix', chatOnly: true,
    autoModel: 'step-3.7-flash:free', autoPriority: 16,
    free: 'Free-suffixed models are capped at 5 RPM and 200 requests per day.',
    models: [
      'step-3.7-flash:free', 'gemma-4-31b-it:free', 'nemotron-3-nano-30b-a3b:free',
      'laguna-xs.2:free', 'laguna-m.1:free', 'nemotron-nano-9b-v2:free',
      'gpt-oss-120b:free', 'llama-3.2-3b-instruct:free', 'llama-3.2-1b-instruct:free',
      'llama-3.1-8b-instruct:free', 'llama-3.3-70b-instruct:free',
    ],
  },
  {
    id: 'naga', name: 'NagaAI', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.naga.ac/v1', env: 'NAGA_API_KEY', publicCatalog: true,
    signup: 'https://naga.ac', modelPolicy: 'free-suffix', chatOnly: true,
    autoModel: 'nemotron-3-super-120b-a12b:free', autoPriority: 18,
    free: 'Orb exposes only zero-priced :free chat routes from NagaAI’s public catalog.',
    models: [
      'nemotron-3-ultra-550b-a55b:free', 'nemotron-3-super-120b-a12b:free',
      'llama-3.3-70b-instruct:free', 'sonar:free', 'llama-4-scout-17b-16e-instruct:free',
    ],
  },
  {
    id: 'poixe', name: 'Poixe AI', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.poixe.com/v1', env: 'POIXE_API_KEY', discover: false,
    signup: 'https://poixe.com', modelPolicy: 'free-suffix',
    autoModel: 'qwen3-8b:free', autoPriority: 25,
    free: 'Free-suffixed chat models have separate daily-reset quotas; Orb seeds only models marked free by Poixe.',
    models: [
      'gpt-3.5-turbo:free', 'gpt-3.5-turbo-0125:free', 'gpt-4.1:free',
      'gpt-4.1-2025-04-14:free', 'gpt-4.1-mini:free', 'gpt-4.1-mini-2025-04-14:free',
      'gpt-4.1-nano:free', 'gpt-4.1-nano-2025-04-14:free', 'gpt-4o:free',
      'gpt-4o-2024-08-06:free', 'gpt-4o-2024-11-20:free', 'gpt-4o-mini:free',
      'gpt-4o-mini-2024-07-18:free', 'gpt-5:free', 'gpt-5-2025-08-07:free',
      'gpt-5-chat-latest:free', 'gpt-5-mini:free', 'gpt-5-mini-2025-08-07:free',
      'gpt-5-nano:free', 'gpt-5-nano-2025-08-07:free', 'gpt-5.1:free',
      'gpt-5.1-2025-11-13:free', 'gpt-5.2:free', 'gpt-5.2-2025-12-11:free',
      'gpt-oss-120b:free', 'gpt-oss-20b:free', 'o1-mini:free', 'o1-mini-2024-09-12:free',
      'o3-mini:free', 'o3-mini-2025-01-31:free', 'o4-mini:free', 'o4-mini-2025-04-16:free',
      'claude-sonnet-4-20250514:free', 'claude-sonnet-4-5-20250929:free',
      'deepseek-chat:free', 'deepseek-reasoner:free', 'doubao-1-5-lite-32k-250115:free',
      'doubao-1-5-pro-256k-250115:free', 'doubao-1-5-pro-32k-250115:free',
      'doubao-1-5-pro-32k-character-250228:free', 'doubao-1-5-thinking-pro-250415:free',
      'doubao-1-5-thinking-vision-pro-250428:free', 'doubao-1-5-vision-pro-32k-250115:free',
      'doubao-1.5-vision-lite-250315:free', 'doubao-1.5-vision-pro-250328:free',
      'doubao-seed-1-6-250615:free', 'doubao-seed-1-6-flash-250615:free',
      'doubao-seed-1-6-thinking-250615:free', 'gemini-2.0-flash:free',
      'gemini-2.0-flash-lite:free', 'gemini-2.5-flash:free', 'gemini-2.5-flash-lite:free',
      'gemini-2.5-pro:free', 'gemini-3-flash-preview:free', 'gemini-3-pro-preview:free',
      'grok-3:free', 'grok-3-beta:free', 'grok-3-mini:free', 'grok-3-mini-beta:free',
      'grok-4:free', 'qwen-long:free', 'qwen-long-2025-01-25:free',
      'qwen-long-latest:free', 'qwen-max:free', 'qwen-max-2025-01-25:free',
      'qwen-max-latest:free', 'qwen-plus:free', 'qwen-plus-2025-04-28:free',
      'qwen-plus-latest:free', 'qwen-turbo:free', 'qwen-turbo-2025-04-28:free',
      'qwen-turbo-latest:free', 'qwen3-0.6b:free', 'qwen3-1.7b:free', 'qwen3-14b:free',
      'qwen3-235b-a22b:free', 'qwen3-235b-a22b-instruct-2507:free',
      'qwen3-30b-a3b:free', 'qwen3-32b:free', 'qwen3-4b:free', 'qwen3-8b:free',
      'qwen3-coder-480b-a35b-instruct:free', 'qwq-plus:free',
      'qwq-plus-2025-03-05:free', 'qwq-plus-latest:free',
    ],
  },
  {
    id: 'meganova', name: 'MegaNova', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://inference.meganova.ai/v1', env: 'MEGANOVA_API_KEY', discover: false,
    signup: 'https://meganova.ai', autoModel: 'meganova-ai/manta-mini-1.0', autoPriority: 28,
    free: 'Tier-1 text models need no credit balance and have per-model daily limits.',
    models: [
      'meganova-ai/manta-mini-1.0', 'meganova-ai/manta-flash-1.0',
      'meganova-ai/manta-pro-1.0', 'deepseek-ai/DeepSeek-V3-0324-Free',
      'Sao10K/L3-8B-Stheno-v3.2', 'Sao10K/L3-70B-Euryale-v2.1',
      'Steelskull/L3.3-MS-Nevoria-70b', 'BruhzWater/Sapphira-L3.3-70b-0.1',
      'FallenMerick/MN-Violet-Lotus-12B', 'mistralai/Mistral-Small-3.2-24B-Instruct-2506',
    ],
  },
  {
    id: 'zylo', name: 'Zylo AI', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.zyloai.net/v1', env: 'ZYLO_API_KEY', publicCatalog: true,
    signup: 'https://zyloai.net', modelPolicy: 'basic-free', chatOnly: true,
    autoModel: 'gpt-oss-20b', autoPriority: 29,
    free: 'Basic plan is card-free; Orb lists only Basic-tier chat models with explicit zero prices.',
    models: [
      'mistral-small-4', 'nemotron-3-ultra', 'gpt-oss-20b', 'qwen-3.5',
      'qwen-3.5-flash', 'mistral-large-3', 'llama-3.2-3b', 'step-3.7',
      'diffusiongemma',
    ],
  },
  {
    id: 'voidai', name: 'VoidAI', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.voidai.app/v1', env: 'VOIDAI_API_KEY', discover: false,
    signup: 'https://voidai.app',
    free: 'Free plan resets 125,000 credits daily; kept out of automatic routing because usage is credit-metered.',
    models: [
      'deepseek-v3.2', 'deepseek-v4-flash', 'deepseek-v4-flash-0731', 'deepseek-v4-pro',
      'glm-5.2', 'gpt-oss-20b', 'kimi-k2.6', 'kimi-k2.7-code', 'kimi-k3',
      'qwen3-coder-480b-a35b-instruct', 'umbra',
    ],
  },
  {
    id: 'poolside', name: 'Poolside', badge: 'FREE PREVIEW', kind: 'cloud', keyless: false,
    baseUrl: 'https://inference.poolside.ai/v1', env: 'POOLSIDE_API_KEY', discover: false,
    signup: 'https://poolside.ai/models',
    free: 'Laguna models are free during the provider’s limited-time public preview.',
    models: ['poolside/laguna-s-2.1', 'poolside/laguna-xs-2.1'],
  },
  {
    id: 'mixlayer', name: 'Mixlayer', badge: 'FREE MODEL', kind: 'community', keyless: false,
    baseUrl: 'https://models.mixlayer.ai/v1', env: 'MIXLAYER_API_KEY', discover: false,
    signup: 'https://mixlayer.ai', modelPolicy: 'free-suffix',
    free: 'The explicit free route is capped by the provider’s free request limits.',
    models: ['qwen/qwen3.5-4b-free'],
  },
  {
    id: 'electronhub', name: 'Electron Hub', badge: 'FREE MODELS', kind: 'community', keyless: false,
    baseUrl: 'https://api.electronhub.ai/v1', env: 'ELECTRONHUB_API_KEY', publicCatalog: true,
    signup: 'https://www.electronhub.ai/rewards', modelPolicy: 'free-suffix', chatOnly: true,
    autoModel: 'deepseek-v4-flash:free', autoPriority: 13,
    free: 'Explicit :free routes use ten daily-reset Neutrinos; ordinary credit-priced routes are excluded.',
    models: [
      'gpt-oss-20b:free', 'gpt-oss-120b:free', 'claude-sonnet-4-5:free',
      'gemma-4-26b-a4b-it:free', 'gemma-4-31b-it:free', 'nemotron-nano-9b-v2:free',
      'nemotron-3-nano-30b-a3b:free', 'nemotron-3.5-lightning:free',
      'deepseek-v3.2:free', 'deepseek-v4-flash:free', 'ministral-3-8b-instruct:free',
      'mistral-small-3.2-24b-instruct:free', 'minimax-m2.7:free',
      'qwen3-coder-30-a3b-instruct:free', 'qwen3.6-27b:free', 'qwen3.6-35b-a3b:free',
      'aion-3.0-mini:free', 'aion-3.0:free', 'glm-4.6:free', 'glm-4.7:free',
      'glm-4.7-flash:free', 'glm-5:free', 'glm-5.1:free', 'glm-5.2:free',
      'kimi-k2.6:free',
    ],
  },
  {
    id: 'navy', name: 'NavyAI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.navy/v1', env: 'NAVYAI_API_KEY', publicCatalog: true,
    signup: 'https://api.navy/dashboard', modelPolicy: 'free-plan', chatOnly: true,
    autoModel: 'nemotron-3-super', autoPriority: 15,
    free: 'Free plan includes 150,000 weighted tokens per day; premium routes are filtered out.',
    models: [
      'schizogpt', 'gemma-4-31b-it', 'gemma-4-26b-a4b-it', 'llama-3.1-8b-instruct',
      'llama-3.3-70b-instruct', 'deepseek-v4-flash-0731', 'deepseek-v4-flash',
      'deepseek-chat', 'deepseek-v3.2', 'mistral-small-2603', 'mistral-small-latest',
      'command-a-plus', 'command-a', 'command-a-vision', 'command-a-reasoning',
      'command-r-7b', 'command-r', 'command-r-plus', 'c4ai-aya-expanse-32b',
      'c4ai-aya-vision-32b', 'gpt-oss-20b', 'gpt-oss-120b', 'qwen3.6-27b',
      'nemotron-3-super', 'hermes-4-70b', 'venice-uncensored',
      'venice-uncensored-role-play', 'deepseek-v4-flash-venice', 'deepseek-v3.2-venice',
      'glm-5-venice', 'glm-5.1-venice', 'glm-5.2-venice', 'glm-4.7-flash-heretic',
      'gpt-4o-mini', 'gpt-4.1-nano',
    ],
  },
  {
    id: 'helyx', name: 'HelyxAI', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://helyxai.space/v1', env: 'HELYXAI_API_KEY', discover: false,
    signup: 'https://helyxai.space', autoModel: 'gemma-4-31B-it', autoPriority: 17,
    free: 'No paid tier or card; standard models share a 2,000,000-token daily allowance.',
    models: [
      'DeepSeek-V4-Flash', 'Kimi-K3', 'MiniMax-M3', 'Mistral-4', 'Qwen3-32B',
      'gemini-3.1-flash-lite', 'gemma-4-31B-it', 'gpt-5.6-luna', 'gpt-oss-120b',
      'llama-3.1-8b-instruct',
    ],
  },
  {
    id: 'yolo-auto', name: 'Yolo-Auto', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://yolo-auto.com/v1', env: 'YOLO_AUTO_API_KEY', discover: false,
    signup: 'https://yolo-auto.com/signup', autoModel: 'qwen3.6-35b-a3b', autoPriority: 19,
    free: 'Card-free Qwen access has a small daily request allowance and no token bill.',
    models: ['qwen3.6-35b-a3b'],
  },
  {
    id: 'freeinference', name: 'FreeInference', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://freeinference.org/v1', env: 'FREEINFERENCE_API_KEY', publicCatalog: true,
    signup: 'https://freeinference.org', chatOnly: true,
    free: 'Research-community service with no card; prompts and responses are logged for research.',
    models: ['glm-5.1', 'minimax-m2.5', 'minimax-m3', 'qwen3.6-35b', 'diffusiongemma', 'deepseek-v4-flash'],
  },
  {
    id: 'mnn', name: 'MNN AI', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.mnnai.ru/v1', env: 'MNN_API_KEY', publicCatalog: true,
    signup: 'https://mnnai.ru', modelPolicy: 'free-plan', chatOnly: true,
    free: 'Free plan receives one monthly credit and exposes only models tagged for the Free tier.',
    models: [
      'gpt-5.2', 'gpt-5.1', 'gpt-5', 'gpt-5-mini', 'gpt-5-nano', 'gpt-4.1',
      'gpt-4.1-mini', 'gpt-4.1-nano', 'gpt-oss-120b', 'gpt-oss-20b', 'o4-mini',
      'gpt-4o', 'gpt-4o-mini', 'o3-mini', 'glm-4.7-free', 'deepseek-v4-flash',
      'deepseek-v3.2', 'deepseek-v3.1', 'mistral-large-latest', 'mistral-medium-latest',
      'magistral-medium-latest', 'mistral-small-latest', 'pixtral-12b-2409',
      'gemini-3.5-flash', 'gemini-3.1-flash-lite', 'gemini-3-flash-preview',
      'step-3.7-flash', 'gemma-4-31b-it', 'qwen-3.5-397b-a17b',
      'qwen-3-coder-plus', 'qwen-3-235b-a22b', 'qwen-3-235b-a22b-2507',
      'nemotron-3-nano', 'sonar',
    ],
  },
  {
    id: 'speka', name: 'Speka', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://speka.me/v1', env: 'SPEKA_API_KEY', publicCatalog: true,
    signup: 'https://speka.me/signup', chatOnly: true,
    free: 'Free plan includes $1 of model usage per month; overage can be metered after billing setup.',
    models: [
      'meta/llama-3.1-8b-instruct', 'minimaxai/minimax-m3', 'mistralai/mistral-nemotron',
      'nvidia/nemotron-3-ultra-550b-a55b', 'stepfun-ai/step-3.7-flash',
      'openai/gpt-oss-20b', 'poolside/laguna-xs-2.1', 'thinkingmachines/inkling',
      'nvidia/nemotron-3-nano-30b-a3b', 'nvidia/nemotron-3-super-120b-a12b',
      'nvidia/nvidia-nemotron-nano-9b-v2', 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
      'meta/llama-3.2-11b-vision-instruct', 'nvidia/nemotron-nano-12b-v2-vl',
    ],
  },
  {
    id: 'intern-ai', name: 'Intern AI', badge: 'FREE TIER', kind: 'cloud', keyless: false,
    baseUrl: 'https://chat.intern-ai.org.cn/api/v1', env: 'INTERN_AI_API_KEY', discover: false,
    signup: 'https://internlm.intern-ai.org.cn',
    free: 'Shanghai AI Laboratory API tokens provide a large research-oriented free allowance.',
    models: [
      'intern-latest', 'intern-s1', 'intern-s1-mini', 'intern-s1-pro', 'intern-s2-preview',
      'intern-s2-preview-35b', 'intern-s2-preview-397b', 'internvl-latest',
      'internvl3.5-241b-a28b', 'internvl3.5-latest',
    ],
  },
  {
    id: 'auriko', name: 'Auriko', badge: 'FREE MODELS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.auriko.ai/v1', env: 'AURIKO_API_KEY', discover: false,
    signup: 'https://www.auriko.ai',
    free: 'Orb seeds only the provider’s three zero-priced GLM Flash routes; other models are metered.',
    models: ['glm-4.5-flash', 'glm-4.6v-flash', 'glm-4.7-flash'],
  },
  {
    id: 'helixmind', name: 'HelixMind API', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://helixmind.online/v1', env: 'HELIXMIND_API_KEY', discover: false,
    signup: 'https://helixmind.online',
    free: 'Free account is limited to 3 RPM and 50 requests/day on four verified models.',
    models: ['deepseek-v4-flash-0731-thinking', 'gpt-oss-20b', 'llama-4-scout', 'qwen3.6-35b-a3b'],
  },
  {
    id: 'tokenreply', name: 'TokenReply', badge: 'FREE TIER', kind: 'community', keyless: false,
    baseUrl: 'https://api.tokenreply.com/v1', env: 'TOKENREPLY_API_KEY', discover: false,
    signup: 'https://www.tokenreply.com',
    free: 'Free-model-only account quota is limited to a few requests per minute and per week.',
    models: [
      'deepseek-ai/deepseek-v4-flash', 'deepseek-v4-flash-free',
      'google/gemma-4-26b-a4b-it', 'nemotron-3-ultra-free',
      'openai/gpt-oss-120b', 'stepfun-ai/step-3.7-flash',
    ],
  },
  {
    id: 'longcat', name: 'LongCat', badge: 'FREE CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.longcat.chat/openai/v1', env: 'LONGCAT_API_KEY',
    signup: 'https://longcat.chat/platform/',
    free: 'New accounts may receive a one-time evaluation grant; later use is metered.',
    models: ['LongCat-2.0'],
  },
  {
    id: 'reka', name: 'Reka', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.reka.ai/v1', env: 'REKA_API_KEY',
    signup: 'https://platform.reka.ai',
    free: 'Account creation is free, but current chat pricing is pay-as-you-go.',
    models: ['reka-flash', 'reka-edge', 'reka-edge-2603'],
  },
  {
    id: 'lighton', name: 'LightOn Paradigm', badge: 'ENTERPRISE', kind: 'cloud', keyless: false,
    baseUrl: 'https://paradigm.lighton.ai/api/v3', env: 'LIGHTON_API_KEY',
    signup: 'https://paradigm.lighton.ai',
    free: 'Paradigm access is provisioned by an organization; usage and model availability depend on its plan.',
    models: ['alfred-4.2', 'alfred-ft5'],
  },
  {
    id: 'writer', name: 'Writer AI Studio', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.writer.com/v1', env: 'WRITER_API_KEY',
    signup: 'https://app.writer.com/aistudio',
    free: 'API usage is metered; availability is controlled by the user’s Writer AI Studio workspace.',
    models: ['palmyra-x5', 'palmyra-x4'],
  },
  {
    id: 'langdb', name: 'LangDB AI Gateway', badge: 'GATEWAY', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'LANGDB_BASE_URL', requiresBaseUrl: true, env: 'LANGDB_API_KEY',
    signup: 'https://app.langdb.ai',
    free: 'Use the project-specific URL shown by LangDB; downstream model charges and workspace limits apply.',
    models: ['anthropic/claude-sonnet-4', 'openai/gpt-4.1', 'openai/gpt-4o-mini'],
  },
  {
    id: 'langdb-local', name: 'LangDB Self-Hosted', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', baseEnv: 'LANGDB_LOCAL_URL', env: 'LANGDB_LOCAL_API_KEY', optionalKey: true,
    signup: 'https://github.com/langdb/ai-gateway',
    free: 'The open-source gateway runs locally; connected upstream models may still incur their own charges.',
    models: ['gpt-oss', 'gpt-4o-mini', 'claude-3-opus'],
  },
  {
    id: 'inference-net', name: 'Inference.net', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.inference.net/v1', env: 'INFERENCE_NET_API_KEY',
    signup: 'https://inference.net/dashboard/api-keys',
    free: 'Account creation is free; hosted open models and custom deployments are billed to the workspace.',
    models: [
      'google/gemma-3-27b-instruct/bf-16',
      'meta-llama/llama-3.2-1b-instruct/fp-16',
      'inference-net/schematron-v2-small',
    ],
  },
  {
    id: 'koyeb-inference', name: 'Koyeb Inference', badge: 'CUSTOM ENDPOINT', kind: 'cloud', keyless: true,
    baseUrl: '', baseEnv: 'KOYEB_INFERENCE_URL', requiresBaseUrl: true,
    env: 'KOYEB_INFERENCE_API_KEY', optionalKey: true,
    signup: 'https://app.koyeb.com',
    free: 'Point Orb at the /v1 URL of a Koyeb-hosted vLLM service; Koyeb compute charges apply.',
    models: ['koyeb/Meta-Llama-3.1-8B-Instruct'],
  },
  {
    id: 'tensorrt-llm', name: 'TensorRT-LLM Serve', badge: 'LOCAL GPU', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', baseEnv: 'TENSORRT_LLM_URL',
    env: 'TENSORRT_LLM_API_KEY', optionalKey: true,
    signup: 'https://github.com/NVIDIA/TensorRT-LLM',
    free: 'Runs locally on NVIDIA GPUs; Orb discovers the model loaded by trtllm-serve.',
    models: ['openai/gpt-oss-120b', 'TinyLlama-1.1B-Chat-v1.0'],
  },
  {
    id: 'mistralrs', name: 'mistral.rs', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:1234/v1', baseEnv: 'MISTRALRS_URL',
    env: 'MISTRALRS_API_KEY', optionalKey: true,
    signup: 'https://github.com/EricLBuehler/mistral.rs',
    free: 'Runs locally across CUDA, Metal, CPU, and other accelerators with no service fee.',
    models: ['default', 'Qwen/Qwen3-4B'],
  },
  {
    id: 'gpustack', name: 'GPUStack', badge: 'SELF-HOSTED', kind: 'local', keyless: false,
    baseUrl: '', baseEnv: 'GPUSTACK_URL', requiresBaseUrl: true, env: 'GPUSTACK_API_KEY',
    signup: 'https://github.com/gpustack/gpustack',
    free: 'The open-source control plane is self-hosted; users supply the /v1 endpoint and an API key.',
    models: ['qwen3-0.6b', 'deepseek-r1-distill-llama-70b'],
  },
  {
    id: 'llama-stack', name: 'Llama Stack', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8321/v1', baseEnv: 'LLAMA_STACK_URL',
    env: 'LLAMA_STACK_API_KEY', optionalKey: true,
    signup: 'https://github.com/llamastack/llama-stack',
    free: 'Runs locally or on user-controlled infrastructure; upstream inference costs depend on its configured provider.',
    models: ['llama-3.3-70b', 'meta-llama/Llama-3.1-8B-Instruct'],
  },
  {
    id: 'apipark', name: 'APIPark', badge: 'GATEWAY', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.apipark.com/v1', baseEnv: 'APIPARK_URL', env: 'APIPARK_API_KEY',
    signup: 'https://apipark.com',
    free: 'Gateway access depends on the models and services subscribed to by the APIPark consumer.',
    models: ['deepseek-v3'],
  },
  {
    id: 'bifrost', name: 'Bifrost AI Gateway', badge: 'LOCAL GATEWAY', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', baseEnv: 'BIFROST_URL',
    env: 'BIFROST_API_KEY', optionalKey: true,
    signup: 'https://github.com/maximhq/bifrost',
    free: 'The open-source gateway runs locally; configured upstream providers retain their own pricing.',
    models: ['openai/gpt-4o-mini'],
  },
  {
    id: 'higress-ai', name: 'Higress AI Gateway', badge: 'LOCAL GATEWAY', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', baseEnv: 'HIGRESS_AI_URL',
    env: 'HIGRESS_AI_API_KEY', optionalKey: true,
    signup: 'https://github.com/alibaba/higress',
    free: 'The community gateway is self-hosted; configured upstream model usage may be billed separately.',
    models: ['qwen-max'],
  },
  {
    id: 'envoy-ai', name: 'Envoy AI Gateway', badge: 'LOCAL GATEWAY', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:1975/v1', baseEnv: 'ENVOY_AI_GATEWAY_URL',
    env: 'ENVOY_AI_GATEWAY_API_KEY', optionalKey: true,
    signup: 'https://github.com/envoyproxy/ai-gateway',
    free: 'The open-source gateway runs locally or in Kubernetes; upstream provider pricing still applies.',
    models: ['gpt-4o-mini'],
  },
  {
    id: 'parasail', name: 'Parasail', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.parasail.io/v1', env: 'PARASAIL_API_KEY',
    signup: 'https://www.saas.parasail.io/keys',
    free: 'Serverless and batch inference are usage-priced; model availability is discoverable through the API.',
    models: ['parasail-llama-33-70b-fp8', 'parasail-deepseek-r1', 'Olmo-3-32B-Think'],
  },
  {
    id: 'vertex-openai', name: 'Google Vertex AI (OpenAI)', badge: 'CLOUD', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'VERTEX_OPENAI_BASE_URL', requiresBaseUrl: true,
    env: 'VERTEX_ACCESS_TOKEN',
    signup: 'https://console.cloud.google.com/vertex-ai',
    free: 'Uses Google Cloud billing; set the project/location OpenAI endpoint and a current OAuth access token.',
    models: ['google/gemini-2.5-flash', 'google/gemini-2.0-flash-001'],
  },
  {
    id: 'kserve', name: 'KServe Generative Inference', badge: 'SELF-HOSTED', kind: 'local', keyless: true,
    baseUrl: '', baseEnv: 'KSERVE_OPENAI_URL', requiresBaseUrl: true,
    env: 'KSERVE_API_KEY', optionalKey: true,
    signup: 'https://kserve.github.io/website/',
    free: 'Runs in the user’s Kubernetes cluster; provide the service URL ending in /openai/v1.',
    models: ['llama3'],
  },
  {
    id: 'redhat-inference', name: 'Red Hat AI Inference Server', badge: 'LOCAL GPU', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', baseEnv: 'REDHAT_INFERENCE_URL',
    env: 'REDHAT_INFERENCE_API_KEY', optionalKey: true,
    signup: 'https://www.redhat.com/en/products/ai/inference-server',
    free: 'Runs on user-controlled GPU infrastructure; registry and Red Hat subscription terms apply.',
    models: ['RedHatAI/Llama-3.2-1B-Instruct-FP8'],
  },
  {
    id: 'nexa', name: 'Nexa SDK', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:18181/v1', baseEnv: 'NEXA_URL',
    env: 'NEXA_API_KEY', optionalKey: true,
    signup: 'https://nexa.ai',
    free: 'Runs models locally through the Nexa SDK with no per-token service charge.',
    models: ['NexaAI/Qwen3-0.6B-GGUF', 'NexaAI/qwen3vl-GGUF'],
  },
  {
    id: 'openvino', name: 'OpenVINO Model Server', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v3', baseEnv: 'OPENVINO_MODEL_SERVER_URL',
    env: 'OPENVINO_MODEL_SERVER_API_KEY', optionalKey: true,
    signup: 'https://github.com/openvinotoolkit/model_server',
    free: 'Runs locally on Intel CPU, GPU, or NPU hardware with no per-token service fee.',
    models: ['OpenVINO/Qwen3-8B-int4-cw-ov'],
  },
  {
    id: 'gaia', name: 'Gaia Node', badge: 'DECENTRALIZED', kind: 'community', keyless: false,
    baseUrl: '', baseEnv: 'GAIA_NODE_URL', requiresBaseUrl: true, env: 'GAIA_API_KEY',
    signup: 'https://www.gaianet.ai',
    free: 'Each Gaia node controls its own access policy; provide the node-specific /v1 URL and key.',
    models: ['model_name'],
  },
  {
    id: 'wandb', name: 'Weights & Biases Inference', badge: 'CREDITS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.inference.wandb.ai/v1', env: 'WANDB_API_KEY',
    signup: 'https://wandb.ai/settings',
    free: 'Requires W&B Inference credits; team and project attribution are optional for personal accounts.',
    models: [
      'moonshotai/Kimi-K2.5', 'openai/gpt-oss-120b', 'openai/gpt-oss-20b',
      'deepseek-ai/DeepSeek-V3-0324', 'deepseek-ai/DeepSeek-R1-0528',
      'meta-llama/Llama-3.3-70B-Instruct', 'meta-llama/Llama-4-Scout-17B-16E-Instruct',
      'microsoft/Phi-4-mini-instruct',
    ],
  },
  {
    id: 'openai-compatible', name: 'Custom OpenAI-Compatible API', badge: 'CUSTOM', kind: 'cloud', keyless: true,
    baseUrl: '', baseEnv: 'OPENAI_COMPATIBLE_BASE_URL', requiresBaseUrl: true,
    env: 'OPENAI_COMPATIBLE_API_KEY', optionalKey: true,
    signup: 'https://platform.openai.com/docs/api-reference/chat',
    free: 'Connect any additional service that implements /models and /chat/completions; its own terms apply.',
    models: ['default'],
  },
  {
    id: 'byteplus', name: 'BytePlus ModelArk', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://ark.ap-southeast.bytepluses.com/api/v3', env: 'BYTEPLUS_ARK_API_KEY',
    signup: 'https://console.byteplus.com/ark/region:ark+ap-southeast-1/apikey',
    free: 'ModelArk usage is metered through the BytePlus account; promotional offers may vary.',
    models: ['seed-2-0-lite-260228'],
  },
  {
    id: 'lamini', name: 'Lamini Inference', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.lamini.ai/inf', env: 'LAMINI_API_KEY',
    signup: 'https://app.lamini.ai/account',
    free: 'Hosted and third-party inference usage depends on the credits and plan attached to the account.',
    models: ['meta-llama/Llama-3.2-3B-Instruct', 'gpt-4o-mini'],
  },
  {
    id: 'apertis', name: 'Apertis', badge: 'CODING PLANS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.apertis.ai/v1', env: 'APERTIS_API_KEY',
    signup: 'https://api.apertis.ai',
    free: 'Offers subscription coding plans and pay-as-you-go access; available models depend on the key type.',
    models: [
      'claude-opus-4-8', 'claude-sonnet-4-6', 'claude-haiku-4-5',
      'gpt-5.5', 'gpt-5.4-mini',
    ],
  },
  {
    id: 'aihubmix', name: 'AIHubMix', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://aihubmix.com/v1', env: 'AIHUBMIX_API_KEY',
    signup: 'https://aihubmix.com',
    free: 'Unified pay-as-you-go gateway; model availability and regional routes can change.',
    models: ['gpt-5.2-codex', 'claude-opus-4-7', 'gemini-2.5-flash', 'gpt-4o-mini'],
  },
  {
    id: 'openshift-maas', name: 'OpenShift AI Models-as-a-Service', badge: 'SELF-HOSTED', kind: 'local', keyless: false,
    baseUrl: '', baseEnv: 'OPENSHIFT_MAAS_URL', requiresBaseUrl: true, env: 'OPENSHIFT_MAAS_API_KEY',
    signup: 'https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.4/html-single/govern_llm_access_with_models-as-a-service/index',
    free: 'Runs in the user’s OpenShift AI cluster; provide the model-specific /llm/<model-name>/v1 URL and its MaaS API key.',
    models: ['model-name'],
  },
  {
    id: 'openshift-ogx', name: 'OpenShift AI OGX', badge: 'SELF-HOSTED', kind: 'local', keyless: true,
    baseUrl: '', baseEnv: 'OPENSHIFT_OGX_URL', requiresBaseUrl: true,
    env: 'OPENSHIFT_OGX_API_KEY', optionalKey: true,
    signup: 'https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.5/html/working_with_ogx/overview-of-ogx_rag',
    free: 'Runs in the user’s OpenShift AI cluster; provide the OGX service URL ending in /v1 and a key if authentication is enabled.',
    models: ['model-name'],
  },
  {
    id: 'openshift-llmd', name: 'OpenShift AI llm-d', badge: 'DISTRIBUTED', kind: 'local', keyless: true,
    baseUrl: '', baseEnv: 'OPENSHIFT_LLMD_URL', requiresBaseUrl: true,
    env: 'OPENSHIFT_LLMD_TOKEN', optionalKey: true,
    signup: 'https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/3.5/html/deploy_models_using_distributed_inference_with_llm-d/',
    free: 'Connects to an llm-d LLMInferenceService /v1 endpoint; a bearer token is required when cluster authentication is enabled.',
    models: ['RedHatAI/Qwen3-8B-FP8-dynamic'],
  },
  {
    id: 'tencent-tokenhub', name: 'Tencent Cloud TokenHub', badge: 'GLOBAL ROUTER', kind: 'cloud', keyless: false,
    baseUrl: 'https://tokenhub-intl.tencentcloudmaas.com/v1', env: 'TENCENT_TOKENHUB_API_KEY',
    signup: 'https://intl.cloud.tencent.com/document/product/1300/80632',
    free: 'International TokenHub access and pricing depend on the Tencent Cloud account and selected model.',
    models: ['hy3', 'deepseek-v4-flash-202605', 'deepseek-v4-pro-202606', 'deepseek-v4-flash', 'deepseek-v4-pro'],
  },
  {
    id: 'tencent-lkeap', name: 'Tencent Cloud LKEAP', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.lkeap.cloud.tencent.com/v1', env: 'TENCENT_LKEAP_API_KEY',
    signup: 'https://cloud.tencent.com/document/product/1772/115969',
    free: 'Uses a separate LKEAP API key and Tencent Cloud billing; DeepSeek workloads are migrating to TokenHub.',
    models: ['deepseek-r1-0528', 'deepseek-v3-0324', 'deepseek-v3.1-terminus', 'deepseek-v3.2'],
  },
  {
    id: 'tencent-edgeone', name: 'Tencent EdgeOne Inference', badge: 'CUSTOM ENDPOINT', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'TENCENT_EDGEONE_URL', requiresBaseUrl: true, env: 'TENCENT_EDGEONE_API_TOKEN',
    signup: 'https://intl.cloud.tencent.com/document/product/1145/78861',
    free: 'Provide the public EdgeOne inference service URL ending in /v1; deployed compute and traffic charges apply.',
    models: ['LLM-Research/Llama-3.2-3B-Instruct'],
  },
  {
    id: 'tencent-tione', name: 'Tencent Cloud TI-ONE', badge: 'CUSTOM ENDPOINT', kind: 'cloud', keyless: true,
    baseUrl: '', baseEnv: 'TENCENT_TIONE_URL', requiresBaseUrl: true,
    env: 'TENCENT_TIONE_API_TOKEN', optionalKey: true,
    signup: 'https://cloud.tencent.com/document/product/851/113484',
    free: 'Connects to the /v1 URL of a user-deployed Angel-vLLM service; TI-ONE infrastructure charges apply.',
    models: ['model-name'],
  },
  {
    id: 'tencent-ai-gateway', name: 'Tencent Cloud AI Gateway', badge: 'GATEWAY', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'TENCENT_AI_GATEWAY_URL', requiresBaseUrl: true, env: 'TENCENT_AI_GATEWAY_API_KEY',
    signup: 'https://cloud.tencent.com/document/product/1826/134818',
    free: 'Provide the configured gateway base URL ending in /v1; gateway and upstream model billing apply.',
    models: ['gpt-4o-mini'],
  },
  {
    id: 'tensorzero', name: 'TensorZero Gateway', badge: 'LOCAL GATEWAY', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:3000/openai/v1', baseEnv: 'TENSORZERO_URL',
    env: 'TENSORZERO_API_KEY', optionalKey: true,
    signup: 'https://www.tensorzero.com/docs/gateway/clients/',
    free: 'The open-source gateway runs locally; credentials and charges belong to its configured upstream providers.',
    models: ['tensorzero::model_name::openai::gpt-5-mini', 'tensorzero::model_name::anthropic::claude-sonnet-4-20250514'],
  },
  {
    id: 'bentoml-local', name: 'BentoML Local Service', badge: 'LOCAL', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:3000/v1', baseEnv: 'BENTOML_LOCAL_URL',
    env: 'BENTOML_LOCAL_API_KEY', optionalKey: true,
    signup: 'https://docs.bentoml.com/en/latest/examples/vllm.html',
    free: 'Runs a BentoML OpenAI-compatible service locally or on user-controlled infrastructure.',
    models: ['meta-llama/Meta-Llama-3.1-8B-Instruct', 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B'],
  },
  {
    id: 'datarobot-gateway', name: 'DataRobot LLM Gateway', badge: 'ENTERPRISE', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'DATAROBOT_LLM_GATEWAY_URL', requiresBaseUrl: true, env: 'DATAROBOT_API_TOKEN',
    signup: 'https://docs.datarobot.com/en/docs/gen-ai/genai-code/dr-llm-gateway.html',
    free: 'Requires an enabled DataRobot LLM Gateway plan; provide the organization endpoint ending in /api/v2/genai/llmgw.',
    models: ['azure/gpt-4o', 'anthropic/claude-sonnet-4'],
  },
  {
    id: 'datarobot-deployment', name: 'DataRobot LLM Deployment', badge: 'CUSTOM ENDPOINT', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'DATAROBOT_DEPLOYMENT_URL', requiresBaseUrl: true, env: 'DATAROBOT_DEPLOYMENT_API_TOKEN',
    signup: 'https://docs.datarobot.com/latest/en/docs/gen-ai/genai-code/genai-chat-completion-api.html',
    free: 'Connects to an LLM blueprint deployment URL; DataRobot platform and underlying model charges apply.',
    models: ['deployment'],
  },
  {
    id: 'traefik-ai', name: 'Traefik Hub AI Gateway', badge: 'GATEWAY', kind: 'local', keyless: true,
    baseUrl: '', baseEnv: 'TRAEFIK_AI_GATEWAY_URL', requiresBaseUrl: true,
    env: 'TRAEFIK_AI_GATEWAY_KEY', optionalKey: true,
    signup: 'https://doc.traefik.io/traefik-hub/ai-gateway/overview',
    free: 'Provide the gateway route ending in /v1; Traefik Hub licensing and upstream model pricing apply.',
    models: ['openai/gpt-5.2-codex', 'anthropic/claude-sonnet-4-6', 'gemini/gemini-3-flash-preview'],
  },
  {
    id: 'wso2-ai', name: 'WSO2 AI Gateway', badge: 'GATEWAY', kind: 'local', keyless: false,
    baseUrl: '', baseEnv: 'WSO2_AI_GATEWAY_URL', requiresBaseUrl: true,
    env: 'WSO2_AI_GATEWAY_API_KEY', authHeader: 'ApiKey', authPrefix: '',
    signup: 'https://apim.docs.wso2.com/en/latest/ai-gateway/overview/',
    free: 'Provide the exposed OpenAI-format API URL and its WSO2 application key; upstream model charges apply.',
    models: ['gpt-5.4', 'claude-sonnet-4-6', 'gemini-2.5-flash'],
  },
  {
    id: 'cloudflare-gateway', name: 'Cloudflare AI Gateway REST API', badge: 'UNIFIED BILLING', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'CLOUDFLARE_AI_GATEWAY_URL', requiresBaseUrl: true, env: 'CLOUDFLARE_AI_GATEWAY_TOKEN',
    signup: 'https://developers.cloudflare.com/ai-gateway/usage/rest-api/',
    free: 'Use the account-specific URL ending in /ai/v1 and a Cloudflare API token; model usage follows Unified Billing.',
    models: [
      'openai/gpt-5.2-codex', 'openai/gpt-4.1', 'anthropic/claude-sonnet-4-5',
      'google-ai-studio/gemini-2.5-flash', 'xai/grok-4',
      '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    ],
  },
  {
    id: 'predibase', name: 'Predibase Dedicated Deployment', badge: 'CUSTOM ENDPOINT', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'PREDIBASE_DEPLOYMENT_URL', requiresBaseUrl: true,
    env: 'PREDIBASE_API_TOKEN', authBodyField: 'api_token',
    signup: 'https://docs.predibase.com/api-reference/inference-api/create-chat-completion',
    free: 'Provide the deployment URL ending in /v1; dedicated deployment and adapter usage is billed by Predibase.',
    models: ['meta-llama/Llama-3.1-8B-Instruct', 'alignment-handbook/zephyr-7b-dpo-lora', 'deployment-model'],
  },
  {
    id: 'nvidia-dynamo', name: 'NVIDIA Dynamo Frontend', badge: 'LOCAL GPU', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8000/v1', baseEnv: 'NVIDIA_DYNAMO_URL',
    env: 'NVIDIA_DYNAMO_API_KEY', optionalKey: true,
    signup: 'https://docs.nvidia.com/dynamo/latest/components/frontend',
    free: 'Runs locally or in the user’s Kubernetes cluster; GPU infrastructure and model licensing are user supplied.',
    models: ['Qwen/Qwen3.5-4B', 'thinkingmachines/Inkling-NVFP4'],
  },
  {
    id: 'lmdeploy', name: 'LMDeploy API Server', badge: 'LOCAL GPU', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:23333/v1', baseEnv: 'LMDEPLOY_URL',
    env: 'LMDEPLOY_API_KEY', optionalKey: true,
    signup: 'https://lmdeploy.readthedocs.io/en/latest/llm/api_server.html',
    free: 'Runs models locally through TurboMind or PyTorch engines with no per-token service fee.',
    models: ['Qwen/Qwen3-Coder-30B-A3B-Instruct', 'internlm/internlm2_5-7b-chat'],
  },
  {
    id: 'llama-box', name: 'llama-box', badge: 'LOCAL · LEGACY', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:8080/v1', baseEnv: 'LLAMA_BOX_URL',
    env: 'LLAMA_BOX_API_KEY', optionalKey: true,
    signup: 'https://github.com/gpustack/llama-box',
    free: 'Runs GGUF models locally; the project is no longer actively maintained and recommends llama.cpp for new setups.',
    models: ['qwen2.5', 'demo'],
  },
  {
    id: 'llama-nexus', name: 'Llama Nexus Gateway', badge: 'LOCAL GATEWAY', kind: 'local', keyless: true,
    baseUrl: 'http://127.0.0.1:3389/v1', baseEnv: 'LLAMA_NEXUS_URL',
    env: 'LLAMA_NEXUS_API_KEY', optionalKey: true,
    signup: 'https://llamaedge.com/docs/llama-nexus/register',
    free: 'The self-hosted gateway routes registered OpenAI-compatible services; upstream provider costs still apply.',
    models: ['registered-model'],
  },
  {
    id: 'poe', name: 'Poe API', badge: 'SUBSCRIPTION POINTS', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.poe.com/v1', env: 'POE_API_KEY',
    signup: 'https://poe.com/api/keys',
    free: 'Poe subscribers can use their included points through the API; additional points can be purchased.',
    models: [
      'Claude-Opus-4.7', 'Claude-Sonnet-4.6', 'GPT-5.4', 'GPT-5.2-Codex',
      'Gemini-3.1-Pro', 'Grok-4.20-Multi-Agent', 'Claude-Haiku-4.5', 'GPT-5-mini',
    ],
  },
  {
    id: 'vast-serverless', name: 'Vast.ai Serverless', badge: 'CUSTOM ENDPOINT', kind: 'cloud', keyless: false,
    baseUrl: '', baseEnv: 'VAST_SERVERLESS_URL', requiresBaseUrl: true, env: 'VAST_API_KEY',
    signup: 'https://docs.vast.ai/guides/serverless/openai-compatible-api',
    free: 'Provide the endpoint-specific openai.vast.ai URL ending in /v1; serverless GPU usage is metered.',
    models: ['Qwen/Qwen3-8B', 'Qwen/Qwen3-30B-A3B'],
  },
  {
    id: 'prime-intellect', name: 'Prime Intellect Inference', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.pinference.ai/api/v1', env: 'PRIME_INTELLECT_API_KEY',
    signup: 'https://app.primeintellect.ai/dashboard/tokens',
    free: 'Token-based inference is deducted from the Prime Intellect account balance; pricing varies by model.',
    models: [
      'meta-llama/llama-3.1-70b-instruct', 'Qwen/Qwen3-4B-Instruct-2507',
      'Qwen/Qwen3-Coder-30B-A3B-Instruct',
    ],
  },
  {
    id: 'routstr', name: 'Routstr', badge: 'BITCOIN · ECASH', kind: 'community', keyless: false,
    baseUrl: 'https://api.routstr.com/v1', env: 'ROUTSTR_API_KEY',
    signup: 'https://routstr.com',
    free: 'Fund a session key with Lightning or use a Cashu token directly; requests spend the attached balance.',
    models: ['gpt-4o', 'gpt-4'],
  },
  {
    id: 'arcee', name: 'Arcee Platform', badge: 'METERED', kind: 'cloud', keyless: false,
    baseUrl: 'https://api.arcee.ai/api/v1', env: 'ARCEE_API_KEY',
    signup: 'https://app.arcee.ai',
    free: 'Wallet-funded inference through Arcee’s direct model API; account credits and pricing apply.',
    models: ['trinity-mini', 'arcee-ai/trinity-mini-thinking', 'arcee-ai/AFM-4.5B'],
  },
  {
    id: 'arcee-conductor', name: 'Arcee Conductor', badge: 'AUTO ROUTER', kind: 'cloud', keyless: false,
    baseUrl: 'https://conductor.arcee.ai/v1', env: 'ARCEE_CONDUCTOR_API_KEY',
    signup: 'https://models.arcee.ai',
    free: 'The free plan can directly invoke Arcee SLMs; third-party frontier routes require an eligible paid account.',
    models: ['auto', 'coder', 'virtuoso-large', 'virtuoso-medium', 'blitz', 'gpt-4.1', 'claude-3-7-sonnet-20250219'],
  },
]);

export const PROVIDER_BY_ID = new Map(PROVIDERS.map(provider => [provider.id, provider]));

export function parseRoute(value) {
  const route = String(value || '').trim();
  const slash = route.indexOf('/');
  if (slash < 1) return { providerId: null, model: route };
  const providerId = route.slice(0, slash).toLowerCase();
  return PROVIDER_BY_ID.has(providerId)
    ? { providerId, model: route.slice(slash + 1) }
    : { providerId: null, model: route };
}

export function routeName(providerId, model) {
  return `${providerId}/${model}`;
}
